RHEnVision/provisioning-backend

deploy/clowdapp.yaml

This is used by the bonfire iqe-cji smoke testing process.
Context: 
https://consoledot.pages.redhat.com/docs/dev/getting-started/ephemeral/smoke.html#_clowdapp_settings

Add testing block to clowdapp spec

---

.github/workflows/gotest.yml
Makefile
README.md
internal/clients/ec2/ec2_client.go
internal/config/config.go
internal/ctxval/ctx_getters.go
internal/dao/dao_interfaces.go
internal/dao/dao_transaction.go
internal/dao/sqlx/account_dao.go
internal/dao/sqlx/pubkey_dao.go
internal/dao/sqlx/pubkey_resource_dao.go
internal/dao/sqlx/sqlx_errors.go
internal/db/connection.go
internal/db/migrations.go
internal/logging/zerolog.go
internal/middleware/duration_metric.go
internal/middleware/find_resource.go
internal/middleware/logger.go
internal/middleware/request_id.go
internal/middleware/request_num.go
internal/payloads/account_payload.go
internal/payloads/error_payload.go
internal/payloads/pubkey_payload.go
internal/services/account_service.go
internal/services/context_logger.go
internal/services/error_renderer.go
internal/services/parameters.go
internal/services/pubkey_service.go

We are already hitting problems with import ordering, this enforces it via GHA.
I am also mergine jobs into three items: formatting, linting, testing. There is no point in running each in its own container.

Enforce goimports to prevent import ordering conflicts

---

internal/payloads/pubkey_payload.go

Copied name of variables did not match what the variable actually holds.
I've noticed this during @lzap's presentation and my OCD did not handle it well xD

Fix variable naming

---

configs/sources_config.yml
internal/clients/sources/client.gen.go

We generated only sources endpoints, but we also need the application 
types.
This is adding that into the config and regenerates the client.

Add application type endpoints for sources

---

.github/workflows/gotest.yml
Makefile

I wanted to test https://github.com/RHEnVision/provisioning-backend/pull/51 locally but I have realized we don't do it in the Makefile. So I moved it there.
On top of that, I implemented the same validation for OpenAPI clients so they are never out of date from the spec we have in the repo.

Validate spec and clients via Makefile

---

api/openapi.gen.json
api/openapi.gen.yaml
cmd/spec/main.go
cmd/spec/path.yaml

This adds errors `responses` to the spec file under `components` for easy referencing from a route.
For motivation see [Reusing responses](https://swagger.io/docs/specification/describing-responses/)

Add error responses to the spec file

---

internal/dao/dao_errors.go
internal/dao/sqlx/pubkey_dao.go
internal/dao/sqlx/pubkey_resource_dao.go
internal/dao/sqlx/sqlx_errors.go

NoRowsError shall wrap the sql.NoRowsErr so we can test for it in inheritance.
This also levels down the error level of logging this error,
it might be expected by the  user.

NoRowsError wrap the original error

---

internal/dao/dao_errors.go
internal/dao/sqlx/sqlx_errors.go

THIS IS A PROPOSAL. I do not feel this is necessary, but IMHO it reads better :)
We are passing errors as pointers, but errors shall be static structures.
No changes should be made to it post creation.
Given performance impact is very small, we can do this to assure correct use of error structures.

Pass errors by value copy

---

internal/config/5_real_config.go

We have forgotten a version in the config from clowder.

Use versioned endpoint for sources

---

internal/services/aws_reservation_service.go
internal/services/pubkey_service.go

After 276e9949346268ab01bc0cbeba1e20be84a5187d the error evaluation stopped working.
We need to test with values, not pointers to values.

HMSPROV-108: Return correct status on not found

---

Makefile
build_deploy.sh
deploy/clowdapp.yaml
pr_check.sh

These will be used by appsre CI for building the main branch image and
pushing to quay.io/cloudservices, and for executing PR checks against
all PRs opened in this repo.
pr_checks will call CI scripts from a shared repo to build an image with
the PR content and run iqe tests against it
build_deploy will execute against the main branch after PR merges.
Executed build_deploy locally, producing and pushing this image:
https://quay.io/repository/mshriver/provisioning-backend?tab=tags

HMSPROV-115: Update makefile, add pr_checks and build_deploy

---

internal/ctxval/context_values.go
internal/dao/sqlx/account_dao.go
internal/dao/stubs/context_getters.go
internal/middleware/account.go
internal/middleware/account_test.go
internal/models/validator.go
internal/testing/identity/dummy_identity.go

Keeping the whole account in the context is bit troublesome.

Keep only account id in the context

---

internal/middleware/account_test.go

Middleware tests do not use the request path.
Having meaningful pathcan be confusing at times.
Also uses t.Errorf for erroring the test out

Use arbitrary path in middleware test

---

cmd/dao_tests/main_test.go
cmd/dao_tests/pubkey_test.go
cmd/dao_tests/reservation_test.go
internal/db/seeds/dao_test.sql

There are two commits in this PR.
The first one improves the DAO tests in general:
* Generic functions were moved into main_test.go and are not exported.
* There are now global `setup` and `teardown` functions and `setupPubkey` etc functions in each file for more specific setup code.
* All setup functions were renamed and broken down into `dbDrop`, `dbMigrate` and `dbSeed` to better reflect what they do.
* Error handling was vastly simplified - for fatal error states (cannot connect to DB, cannot migrate or seed) using `panic` is completely fine because this is a fatal state anyway. Setup functions themselves no longer return errors which makes the code longer due to use of panic keyword.
* Teardown functions are called via `defer`.
The second commit then switches from migrating the …

Use setup/teardown for DAO tests, truncate tables instead of seeding

---

cmd/pbapi/main.go
configs/local_example.yaml
internal/clients/clients_interfaces.go
internal/clients/image_builder/image_client.go
internal/clients/image_builder/stubs/image_builder_stub.go
internal/clients/proxy_doer.go
internal/clients/sources/sources_client.go
internal/clients/sources/stubs/sources_stub.go
internal/config/main_config.go
internal/headers/headers.go
internal/routes/all_routes.go
internal/services/status_service.go
scripts/rest_examples/http-client.env.json
scripts/rest_examples/status-ready-ib.http
scripts/rest_examples/status-ready-sources.http
scripts/rest_examples/status-ready.http

This patch is continuation of https://github.com/RHEnVision/provisioning-backend/pull/150
The idea is to introduce HTTP client configurable proxy per individual service (sources, ib). This is meant for development use against stage. Unfortunately, RHID header cannot be used in this scenario, therefore optional basic auth was added. This is only meant for development, in test/stage/prod environments the basic auth will be blank therefore RHID will be passed instead.

Client proxy support with basic auth for stage

---

internal/dao/stubs/model_factories.go
internal/dao/stubs/stub_errors.go
internal/services/pubkey_service_test.go
internal/testing/factories/factories.go

Factories should be usable in unit and DAO tests alike.
Adding `testing/factories` package, that should host model generation methods for tests.

Generalize testing factories

---

Makefile
cmd/pbapi/main.go
internal/logging/zerolog.go
internal/middleware/version.go
internal/version/version.go

I just experienced what I believe was a testing of an incorrect build artifact. It is worth adding version information (sha commit, build date and time) into HTTP header as well as logs. It should be safe to show this for every request, but I will confirm on Slack.
This patch adds exactly that, all log lines contain "version" string which holds the commit sha. All responses contain new X-Rh-Version header which contains the same plug date and time (in UTC) of comiplation.
When compiling this via IDE (e.g. not via Makefile) no version information will be provided, thus the header will not be present. The same for log field.

Add version information to header and logs

---

.gitignore
api/openapi.gen.json
api/openapi.gen.yaml
cmd/spec/main.go
cmd/spec/path.yaml
scripts/rest_examples/http-client.env.json

We need to start differentiating between the two because for some endpoints (likely /reservations) these are going to look different.
QA: Nothing is changing effectively, these identifiers are for internal use. Generated clients might change internal structure names tho.

Use Request/Response suffixes in OpenAPI schemas

---

internal/middleware/logger.go

They can be quite long and in development we do cut the messages.
**Checklist**

Use message instead of field for panic messages

---

configs/local_example.yaml
internal/config/main_config.go
internal/logging/zerolog.go
internal/logging/zerolog_test.go
internal/middleware/logger.go

Also puts the panic contents (the error string) into the message as it was not presented. Finally, fixes the truncating quoting - when it's quoted close the quote, otherwise do not close it.
**Checklist**

Make log field truncating configurable

---

configs/local_example.yaml
internal/clients/image_builder/image_client.go
internal/clients/interface_doer.go
internal/clients/logging_doer.go
internal/clients/sources/sources_client.go
internal/config/main_config.go

Adds optional (opt-in) logging for all requests and responses done via our HTTP clients (not AWS, can be added later). When turned on, full request and response body is logged as a logging message. Additional fields like URL or status code are added too with a flag that allows searching for such logs which could be helpful in stage environment.
This flag must be not set in production as whole bodies are loaded into byte slices into memory without any limitation.
An example:
```
12:09PM TRC Proxy request to https://console.xxxx.redhat.com/api/image-builder/v1/ready via http://xxxxx.redhat.com:3128 account_number=13 bytes_in=0 hostname=mone.home.lan method=GET org_id=000013 remote_ip=127.0.0.1:50105 rid=cc2aernm1tugokqq9100 rn=2 url=/api/provisioning/v1/ready/ib
12:09PM TRC …
```

Configurable HTTP client body logging

---

api/openapi.gen.json
api/openapi.gen.yaml
cmd/spec/path.yaml
configs/local_example.yaml
internal/clients/ec2/ec2_client.go
internal/config/main_config.go
internal/dao/sqlx/reservation_dao.go
internal/db/migrations/005_reservations.sql
internal/jobs/launch_instance_aws.go
internal/models/reservation_model.go
internal/payloads/reservation_payload.go
internal/services/aws_reservation_service.go
internal/userdata/cloud_init.go
internal/userdata/cloud_init_test.go
internal/userdata/userdata.goyaml
scripts/rest_examples/reservation-create-aws.http

In order to safely and efficiently test on our AWS development accounts, we need a reliable way of keeping our bills low.
One measurement is to automatically launch instances with userdata setting that will immediately power off the instance after it was launched. This can be achieved via the new PowerOff flag. Set it to true for development purposes and your instances will be shut down which is significantly cheaper than running them when not terminated on time.
Second measurement is to introduce instance name. Although we will not use it in the UI at this stage, it is very useful to set instance names to something meaningful. Especially when paired with a new setting called instancePrefix and cloudwash script that is able to automatically terminate or stop instances starting with a …

Add reservation name and poweroff flags

---

api/openapi.gen.json
api/openapi.gen.yaml
cmd/dao_tests/reservation_test.go
internal/clients/ec2/ec2_client.go
internal/ctxval/context_values.go
internal/dao/dao_interfaces.go
internal/dao/sqlx/reservation_dao.go
internal/dao/stubs/reservation_dao.go
internal/db/migrations/005_reservations.sql
internal/jobs/common.go
internal/jobs/launch_instance_aws.go
internal/jobs/noop_job.go
internal/jobs/pubkey_upload_aws_job.go
internal/jobs/queue/queue_types.go
internal/models/reservation_model.go
internal/payloads/reservation_payload.go
internal/services/aws_reservation_service.go
internal/services/noop_reservation_service.go

The list of fields in aws details table was only growing. Most of the fields, however, are informative and they are only passed into jobs as inputs. They are saved only when user wants to fetch existing reservation for more details.
It makes sense to store these fields as a native JSON (JSONB) because we will need to unlikely search or order these fields. This patch does exactly that.
On top of that change, instance name can be now an array so instances can be named separately. There is, however, one big problem with that - AWS API does not allow naming instances in batches, all get the same name.
The patch improves error handling of jobs, we simply ignored errors so far. Now we properly fail reservation with "Error: xxx" status and Success bool is set to false as it was meant.
Therefore, …

Use JSONB for reservation details and improve error handling

---

internal/clients/clients_errors.go
internal/clients/http/ec2/ec2_client.go
internal/clients/http/ec2/ec2_errors.go
internal/jobs/pubkey_upload_aws_job.go
internal/payloads/error_payload.go
internal/services/instance_types_service.go

Adds explicit param missing error.
Adds Unauthorized error in clients, for global clients use and refactors the ec2 client to throw this error.

Improve EC2 error handling

---

api/openapi.gen.json
api/openapi.gen.yaml
configs/local_example.yaml
internal/clients/clients_interfaces.go
internal/clients/http/ec2/ec2_client.go
internal/clients/stubs/ec2_stub.go
internal/config/0_common_config.go
internal/config/main_config.go
internal/jobs/launch_instance_aws.go
internal/jobs/pubkey_upload_aws_job.go
internal/models/reservation_model.go
internal/payloads/reservation_payload.go
internal/services/aws_reservation_service.go
internal/services/instance_types_service.go

Reservation endpoint was missing a region to deploy into.
We are using one region for now, but we need this for future use.

Region aware reservation endpoint 

---

.gitignore
Makefile
internal/config/5_integration_config.go
internal/config/5_normal_config.go
internal/config/main_config.go
internal/config/parser/known.go
internal/dao/tests/account_test.go
internal/dao/tests/main_test.go
internal/dao/tests/pubkey_resource_test.go
internal/dao/tests/pubkey_test.go
internal/dao/tests/reservation_test.go

Fixes configuration of tests, add missing ENV variable and adds NoError in all DAO tests.
Three commits, see commit messages for more details.
ACTION REQUIRED: This patch also fixes configuration loading, it now properly finds the path to the config file. Please move your `cmd/dao_test/local.yaml` to `configs/local.integration.yaml` to get it loaded properly.

Fix integration config loading, introduced NoError in tests

---

internal/services/aws_reservation_service_test.go
internal/services/instance_types_service_test.go
internal/services/noop_reservation_service_test.go
internal/services/pubkey_service_test.go
internal/services/sources_service_test.go

Puts all service tests under the services_test package.
Uses require for cases where we want to stop further test execution
Unify failures handling accros the test files.

Unify service test assertions and error handling

---

.gitignore
Makefile
docs/dev-environment.md
docs/make.md
mk/0_initial.mk
mk/clients.mk
mk/code.mk
mk/compile.mk
mk/container.mk
mk/db.mk
mk/deps.mk
mk/help.mk
mk/openapi.mk
mk/test.mk
mk/tools.mk
mk/types.mk
mk/z_common.mk

No changes in the Makefile other than split. Inspired from https://github.com/content-services/content-sources-backend/tree/main/mk and big thanks for the AWK command which generates the help page.
I haven't implemented the loading as it was designed there, I am using include glob to pick all the mk files.
There are some targets which we might adopt as well, feel free to review and we might pull something from there. Container looks interesting, they support both docker and podman. That could be nice.

Split Makefile and create devel docs

---

api/embed.go
internal/config/parser/known.go
internal/config/parser/viper.go
internal/dao/dao_interfaces.go
internal/middleware/etag_middleware.go
internal/middleware/etag_middleware_test.go
internal/routes/all_routes.go

This new middleware can be used to cache any static or nearly static content. Everything works transparently, as long as a valid etag (string, hash, datetime, timestamp, anything unique) is provided and expiration time is set.
Caching works transparently in browsers, it will not work when API is hit from a curl utility of course.
The OpenAPI caching is just an example, this will be useful for instance types endpoint once we start embedding them into the application instead of dynamically loading them every time.
It can be also useful for any content that was cached in the future.
I tested it works fine with JSON spec, however, I am trying to open up redoc documentation and it simply renders JSON …

ETag middleware with implementation for OpenAPI

---

internal/clients/filter_instances_test.go
internal/clients/http/azure/types/azure_types.go
internal/clients/http/ec2/aws_supported_types.go
internal/clients/instance_type.go
internal/payloads/error_payload.go
internal/payloads/instance_types_payload.go
internal/routes/all_routes.go
internal/services/builtin_types_service.go
internal/services/instance_types_service.go
internal/services/instance_types_service_test.go
internal/services/parameters.go
scripts/rest_examples/instancetypes-azure-list.http

This adds a new endpoint, since we don't have Azure sources integration yet, I am adding it as a separate endpoint that is also documented as undocumented :-) Meaning, there is no OpenAPI for this endpoint, it can be used for quick lookups in the instance type database without having any source record. I propose to keep such endpoint for our own development purposes.
This can serve as an example how to implement the same for EC2 for @avitova. In that case, we already have sources integration so both `/sources/ID/instance_types` and `/instance_types` should be implementing returning the very same results. Note EC2 endpoint currently only supports region, we need to add zones as well.

Add azure instance types endpoint

---

internal/dao/dao_interfaces.go
internal/dao/sqlx/pubkey_resource_dao.go
internal/dao/tests/pubkey_resource_test.go
internal/jobs/pubkey_upload_aws_job.go

Rename pubkey reservation dao methods.
This might be bit too much to add prefix, suffix might have enough visibility, happy to change to whatever we agree on :)

Pubkey resource unscoped by account

---

internal/clients/http/ec2/ec2_client.go
internal/clients/http/sources/sources_client.go
internal/clients/instance_type_info.go
internal/clients/interface.go
internal/clients/stubs/sources_stub.go
internal/payloads/instance_types_payload.go
internal/payloads/pubkey_payload.go
internal/payloads/reservation_payload.go
internal/payloads/sources_payload.go

I have realized that we do unnecessary `append` calls when copying slices from one to the other when length is fixed (known before). In these cases, it's actually more efficient and more readable to allocate array buffer to the exact size and copy without append call.
@ezr-ondrej @avitova @adiabramovitch @amirfefer

Avoid appending when copying slices

---

deploy/clowdapp.yaml

Addressing SRE integration failure, same for MEMORY_REQUESTS.
```
The ClowdApp "provisioning-backend" is invalid: 
* spec.deployments[0].podSpec.resources.requests.cpu: Invalid value: "${CPU_REQUESTS}": spec.deployments[0].podSpec.resources.requests.cpu in body should match '^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?$'
```
**Checklist**
- [ * ] https://github.com/RHEnVision/provisioning-backend#contributing
- [ * ] https://github.com/RedHatInsights/secure-coding-checklist

Add CPU and MEMORY _REQUESTS parameter defaults

---

.github/workflows/gotest.yml
.golangci.yml
internal/clients/http/ec2/ec2_client.go
internal/clients/stubs/ec2_stub.go
internal/clients/stubs/sources_stub.go
internal/clients/supported/filter_instances_test.go
internal/middleware/account_test.go
internal/ptr/any.go
internal/ptr/from.go
internal/ptr/to.go
internal/testing/identity/dummy_identity.go
mk/code.mk
mk/tools.mk

Up until now we used the `ptr` package from smithy library. With Go 1.18, we can now take advantage of generics and have a single function `ptr.To` that will work with any type. This patch creates a new `internal/ptr` package with functions `To` and `From` for easy pointer copying. On top of that, there are also `ToInt64` (and 32) variants so you don't have to type `ptr.To(int64(42))` for constants because the default type for number is `int`.
Feel free to add new functions for other types (unsigned ints) or floats if needed: https://go.dev/tour/basics/11

Package ptr with generics

---

.github/workflows/gotest.yml
docs/dev-environment.md
docs/make.md
mk/code.mk
mk/db.mk
mk/help.mk
mk/z_common.mk
scripts/check_migrations.sh

This makefile/CI job will enforce that no migration files are modified, only added/deleted files are allowed. The makefile target has a nice explanation of what happened and guides you through the process of either skipping the check (by creating an extra/empty commit), or generating a new migration file using the tern utility.
It is executed on GH after integration tests, it's better to run it after because if someone skips the check via the extra commit, tests must be passing.
I also moved few things around in makefile, updated the makefile document markdown and fixed migration target which was still using gomigrate instead of the new tern utility.

Add a make/CI target to check migration changes

---

api/openapi.gen.json
api/openapi.gen.yaml
cmd/spec/path.yaml
internal/dao/dao_interfaces.go
internal/dao/sqlx/reservation_dao.go
internal/dao/stubs/reservation_dao.go
internal/db/migrations/010_rename_provider_detail.sql
internal/models/reservation_model.go
internal/routes/all_routes.go
internal/services/error_renderer.go
internal/services/reservations_service.go
scripts/rest_examples/reservation-aws-get-1.http
scripts/rest_examples/reservation-get-1.http

Although I thought for all filtering we would use URL parameters and provider type can be seen as a filter, because of OpenAPI, we must use the provider in the URL because payloads can be different only for different URLs in OpenAPI.
This adds a new endpoint `/reservations/TYPE/ID` that returns reservation with all the details loaded, currently it only works for AWS but the code is ready for extension.
I am leaving the old `/reservations/ID` still active, it returns only generic information and it can be useful for UI to get just basic info for the progress bar. Should be a tad faster as it does not need to join the two tables, so it's a better fit for polling.
There is still the open question for possible conflict between `TYPE` and `ID`, but I don't see this as a problem until someone …

HMSPROV-285: Reservation detail for AWS

---

.github/workflows/gotest.yml

This just pins the linter because of an error. I think we should simply keep it pinned and casually update it as `latest` breaks quite often.
The reason: https://github.com/golangci/golangci-lint-action/issues/535

Pin linter to 1.47.3

---

.github/workflows/gotest.yml

Our "do not touch migrations" check does not work on CI because it creates a shallow git checkout by default :-)
This should fix this.

Fetch HEAD^ for DAO tests

---

internal/clients/architecture.go
internal/clients/stubs/ec2_stub.go
internal/clients/supported/filter_instances_test.go

I have renamed x86_64 architectures. We are using types.ArchitectureTypeX8664 from ec2 package. I hope that it will not confuse us in the future.

Rename architectures X86_64

---

build/RedHat.dockerfile
build/Upstream.dockerfile
deploy/clowdapp.yaml

This should launch a backend worker alongside with the API service. It's in memory mode, meaning it's useless for now. I will configure dbjobqueue or sqs soon, I just want to test the deployment for now at this point.
Feel free to merge if this passes and I will do followup PRs, I want to take slow steps with this :-)

Launch worker alongside api

---

go.mod
go.sum
internal/db/connection.go

I know I know, another beta dependency! This one is really cool, just hit `/metrics` with this patch:
```
pgxpool_acquire_count{db_host="nuc",db_name="pb_dev",service="provisioning"} 6
pgxpool_acquire_duration_ns{db_host="nuc",db_name="pb_dev",service="provisioning"} 1.196325e+07
pgxpool_acquired_conns{db_host="nuc",db_name="pb_dev",service="provisioning"} 0
pgxpool_canceled_acquire_count{db_host="nuc",db_name="pb_dev",service="provisioning"} 0
pgxpool_constructing_conns{db_host="nuc",db_name="pb_dev",service="provisioning"} 0
pgxpool_empty_acquire{db_host="nuc",db_name="pb_dev",service="provisioning"} 1
pgxpool_idle_conns{db_host="nuc",db_name="pb_dev",service="provisioning"} 3
pgxpool_max_conns{db_host="nuc",db_name="pb_dev",service="provisioning"} 100 …
```

Add prometheus pgx metrics

---

deploy/clowdapp.yaml

This will fail until https://gitlab.cee.redhat.com/insights-qe/iqe-provisioning-plugin/-/blob/master/iqe_provisioning/conf/provisioning.default.yaml#L56 is updated too. Not sure how to approach this without breaking the pipeline tho.
@RHEnVision/qe

Rename clowder service to 'api'

---

api/openapi.gen.json
api/openapi.gen.yaml
cmd/spec/path.yaml

SSIA
Note: only EC2 and Azure are implemented. Also keep in mind that region and zone are required only for some clouds:
* EC2: region required, zone not (must not be passed in)
* Azure: region required, zone required

Add the new instance_types to OpenAPI

---

.chglog/config.yml
CONTRIBUTING.md
docs/dev-environment.md
scripts/check_commits.sh

The CI check did not allow commit messages without component: `feat: no component`.
This fixes it, also sorts all possible types and sync them with the check script (and configuration of the changelog tool).
Finally, adds some documentation.

changelog: update types and add docs

---

config/ib_api.yaml
config/sources_api.json
internal/clients/http/image_builder/client.gen.go
internal/clients/http/sources/client.gen.go
mk/clients.mk

After the `configs` directory rename, the timestamps for `make` were not correct. This fixes it (just by running `make` once).
Also I updated clients, it now contains the change I submitted to sources (missing type, enums).
Finally, I realized that `make generate-clients` target was not documented at all.

chore(oapi): update clients, missing make doc

---

scripts/sources.seed.sh

An unique index was created recently in sources which prevents from bulk creations of multiple sources. This breaks the seed operation into three distinctive requests.
https://github.com/RedHatInsights/sources-api-go/pull/326

chore(scripts): update sources seed script

---

deploy/clowdapp.yaml

Allows to passimage builder URL in non-clowder environments.
Other apps are passing parameter IMAGEBUILDER_URL, so we've decided to keep the same convention.
But internaly we prefer IMAGE_BUILDER_URL format internaly, thus the discrepancy.
We pass the env variable to both `api` and `worker`.

build(deploy): Allow passing image builder url

---

deploy/clowdapp.yaml
internal/config/helpers.go
internal/logging/zerolog.go

SSIA
Looks ugly, e.g. https://ci.int.devshift.net/job/RHEnVision-provisioning-backend-pr-check/464/artifact/artifacts/k8s_artifacts/ephemeral-ewuczi/logs/provisioning-backend-api-service-7d8b9d888c-kn7tc_provisioning-backend-api-service.log
However, I don't know how to test this because our CI does not archive logs when job is successful. Any ideas @RHEnVision/qe ? :-)

Do not use colors for logs when clowder is active

---

.gitignore
internal/clients/http/ec2/types/ec2_types.go

Two small things I ran into today, the ec2 prefix is obvious and was spotted by @adiabramovitch 
The other commit is just a small change - I now have a symlink and it looks like git does not recognize symlinks with `something/` gitignore pattern as the slash requires it to be a directory. This fixes it.

Typo in etag prefix and gitignore update

---

cmd/pbapi/main.go
docs/openapi/index.html
internal/routes/all_routes.go
internal/services/welcome_service.go
internal/version/version.go

This adds a nice welcome page, this is pure HTML 3.2 how I remember it. Here is a screenshot:
The reason was I was hitting `/docs/` instead of the correct `/docs`, I don't need to remember this anymore with this patch. Also shows current version and sha commit on the page (when compiled in).
Also cleans up routes a bit, it was a bit confusing to me.
Finally, adds an `index.html` file which should be available on through github to always show us latest and greatest OpenAPI documentation. Untested but it should work as this is exactly how Go redoc does it (I actually copy and pasted the HTML from there).

feat: welcome HTML page

---

deploy/clowdapp.yaml
internal/config/config.go

We now have IB in ephemeral, so adding the `image-builder` as optional dependency, not to break stage (where image-builder is still not deployed with clowder).
This will find IB config through clowder if there is one, but will not force it's presence.

Add image builder as clowder dependency

---

cmd/pbapi/main.go

Mainly to disable logging for ping route, but other middlewares shall be enabled for application routes only too.
Fixes HMSPROV-333

fix(logging): Disable middlewares for status routes

---

internal/config/config.go
internal/config/flags.go

From others I'm guessing that this should fix unleash connection when token is required.
Also uses unleash project.

fix(config): unleash token as bearer header

---

api/openapi.gen.json
api/openapi.gen.yaml
cmd/spec/path.yaml

This helps IQE to pass the parameters into **kwargs instead of an positional arg.
The same is already done with POST /pubkeys

feat(refactor): Add required true post aws in apispec

---

internal/models/reservation_model.go
internal/payloads/reservation_payload.go

When reservation is created and it is still not fulfilled, the AWS reservation id was NULL in the database, but the struct field was string and not pointer to string. This caused scany library not to be able to scan the `nil` value. This fixes it.
OpenAPI clients must be aware that the field can be `null` in case the reservation is not yet finished.

fix: null for aws_reservation_id when pending

---

deploy/clowdapp.yaml

I noticed that cache is actually not configured for the API pod on ephemeral:
```
7:36AM TRC Registered unleash client: {AppName:provisioning InstanceID:1001900000-provisioning-backend-api-7d85475bc4-f9mbp SDKVersion:unleash-client-go:3.7.0 Strategies:[default applicationHostname gradualRolloutRandom gradualRolloutSessionId gradualRolloutUserId remoteAddress userWithId flexibleRollout] Started:2022-11-21 07:36:51.163013346 +0000 UTC m=+0.577366699 Interval:60} hostname=provisioning-backend-api-7d85475bc4-f9mbp unleash=true version=eb5e353
7:36AM INF No application cache in use hostname=provisioning-backend-api-7d85475bc4-f9mbp version=eb5e353
7:36AM DBG Initializing 'redis' job queue hostname=provisioning-backend-api-7d85475bc4-f9mbp version=eb5e353
7:36AM DBG Starting dequeue loop …
```

fix: missing cache type variable for api

---

internal/clients/http/sources/sources_client.go
internal/clients/http/sources_errors.go

In accounts list we allow to select source that does not contain ARN for provisioning.
When selected and sent to reservation creation with such source following panic ocurs:
```
3:35PM ERR Unhandled panic: runtime error: invalid memory address or nil pointer dereference
goroutine 2312 [running]:
runtime/debug.Stack()
/usr/local/go/src/runtime/debug/stack.go:24 +0x65
github.com/RHEnVision/provisioning-backend/internal/middleware.LoggerMiddleware.func1.1.1()
/build/internal/middleware/logger.go:46 +0x392
panic({0x21580c0, 0x39ab360})
/usr/local/go/src/runtime/panic.go:838 +0x207
github.com/RHEnVision/provisioning-backend/internal/clients/http/sources.(*sourcesClient).GetAuthentication(0xc000546280, {0x29824b8, 0xc001063a10}, {0xc000ad90d0, 0x6}) …
```

fix(sources): handle source without application type correctly

---

internal/background/availability_queue.go
internal/clients/http/platform_client.go
internal/kafka/kafka.go

When I was working with Adi on Kafka producer, I noticed few bugs in my code.
FIrst, the consumer did not break on context cancel correctly which has no effect any other than if you use some method to wait until goroutine is finished e.g.:
```go
ctx := context.Background()
ctx, cancel := context.WithCancel(ctx)
receiverWG.Add(1)
go func() {
defer receiverWG.Done()
// suppose this is kafka.Consume(ctx, ...)
receiveFromKafka(ctx, "a message")
}()
// wait until term signal and then
// stop kafka receiver (can take up to 10 seconds) and wait until it returns
cancel()
receiverWG.Wait()
```
The `Wait` call would never end. The first commit fixes it.
Second, we use a custom HTTP client doer for Sources and IB, however, it creates a new transport for each and every client. This is wasting of …

Multiple Kafka concurrency fixes

---

internal/config/config.go

Clowder types are a mess, some values are pointers (port) others are not (hostname).
People sometimes use pointers to be able to use `nil` and it's bad practice, zero values are also valid options, specifically for port it is definitely a not valid port number.

fix: kafka port is a pointer

---

build/Dockerfile
build_deploy.sh
pr_check.sh

Build by official build container as it supports go 1.18 finaly. Also remove now unused links to ci scripts.
https://issues.redhat.com/browse/HMSPROV-365

build(container): Switch back to oficial go-tool build

---

cmd/pbapi/main.go
cmd/pbstatuser/main.go
internal/background/availability_queue.go
internal/kafka/kafka.go
internal/kafka/noop.go

Just to see little bit more from Kafka:
* list of hosts
* when a message is really sent
* increases to trace for ephemeral
The trace is a bit dirty but I am not sure how can I set options for clowder. It has some CLI arguments but it's cryptic without examples. If I knew how to use its `-p component/parameter=value` then we could ask QE folks to increase verbosity for PR checks.

feat: better Kafka logging

---

internal/config/config.go

Looks like we forget to actually enable Kafka when running in Clowder environment. This does it.

feat: enable Kafka in Clowder

---

internal/dao/dao_interfaces.go
internal/dao/pgx/pubkey_pgx.go
internal/dao/stubs/pubkey_dao.go
internal/dao/tests/pubkey_resource_test.go
internal/jobs/pubkey_upload_aws_job.go

For AWS the key needs to be available in a region we Launch in.
This fixes the search so we verify pubkey for given account and region.
Fixes: HMSPROV-366

fix: scope existing pubkey search by source id

---

internal/clients/http/sources/sources_client.go
internal/clients/http/sources/sources_client_test.go

Adds test that uses [`httptest.Server`](https://pkg.go.dev/net/http/httptest#Server) to mock the outbound connection and stub its response.
I believe this is the best way to test the clients as it tests the client implementation together with the generated client and stubs on the HTTP layer.

test: add unit test for Authentication failure

---

CONTRIBUTING.md
api/openapi.gen.json
api/openapi.gen.yaml
internal/payloads/error_payload.go

We could definitely use these values after a user encounters an error.

feat: add Version and BuildTime to ResponseError

---

.rhcicd/pr_check.sh

When UI test runs, it errors out because `selenium` is not passed along with it, resulting in session error.
This should fix those error and run only api tests.

ci: Update iqe markers for backend

---

internal/config/config.go
internal/config/helpers.go
internal/kafka/kafka.go
internal/kafka/source_result.go
internal/kafka/topics.go
scripts/kafka.start.sh

https://issues.redhat.com/browse/HMSPROV-343
We cannot use topics directly, there is some sort of "prefix" on the platform that is provided by the clowder. This should fix the stage, I am unable to test this until we deploy it on stage.
Also adds some debugging statements when adding the CA cert. It is a public key cert so it is safe to log into debug.

fix: utilize clowder topic mapping

---

internal/dao/tests/main_test.go

This was the only way for me to run `make integration-tests` with the config in the main `config/` folder.
Happy to discuss better options, but if I run the make from root folder, it needs to respect configs from the main config folder, otherwise it is very weird for devs.
Taken out from other PR after a bit of discussion: https://github.com/RHEnVision/provisioning-backend/pull/315/files#r1038972780

test: use path to the main config dir

---

internal/kafka/avail_status_msg.go
internal/kafka/kafka.go
internal/kafka/message.go
internal/kafka/message_test.go
mk/code.mk

Kafka headers are slices instead of map, this is how Kafka does it, we should follow what the library does.
https://issues.redhat.com/browse/HMSPROV-337

fix: Kafka headers are slice now

---

api/openapi.gen.json
api/openapi.gen.yaml
cmd/spec/main.go
cmd/spec/path.yaml
internal/routes/all_routes.go
scripts/rest_examples/availability-status.http

We can start testing in ephemeral where Kafka does work already. For stage, we are still working on a clowder mapping of topics, there is an open PR for that. This one will be a challenge to test:
* Hit the endpoint with an existing source ID that has a AWS account associated.
* Listen for the `platform.sources.event-stream` Kafka event that contains the source ID and result.
* Results can be cached in stage/prod, however, in ephemeral we should not be doing any caching so the event should be sent always (with a small delay of approx. 10 seconds).
Let's try if our checker likes URLs too:
https://issues.redhat.com/browse/HMSPROV-337

feat: introduce availability status endpoint

---

internal/clients/http/ec2/ec2_client.go
internal/clients/http/ec2_errors.go
internal/clients/interface.go
internal/clients/stubs/ec2_stub.go
internal/dao/dao_interfaces.go
internal/dao/pgx/reservation_pgx.go
internal/dao/stubs/context_getters.go
internal/dao/stubs/pubkey_dao.go
internal/dao/stubs/reservation_dao.go
internal/dao/tests/reservation_test.go
internal/jobs/common.go
internal/jobs/ensure_pubkey_on_aws_job.go
internal/jobs/ensure_pubkey_on_aws_job_test.go
internal/jobs/launch_instance_aws.go
internal/jobs/queue/dejq/dejq_queue.go
internal/jobs/queue/queue_types.go
internal/models/reservation_model.go
internal/services/aws_reservation_service.go

Ensure pubkey is on AWS and save its name to ASWDetails.
Fixes: HMSPROV-339 HMSPROV-332
Refactors the pubkey job to Ensure the pubkey exists on AWS.
First it tries to look for the key on AWS, if it exits, it gets its name.
If it doesn't exist, it imports the key with the name we have in our DB.
This name gets saved to AWS details so next job can fetch it and pass the correct name to AWS `RunInstances`.
Adds tests for the refactored job.

fix: ensure pubkey is always present on AWS

---

internal/clients/stubs/ec2_stub.go
internal/jobs/ensure_pubkey_on_aws_job.go
internal/jobs/ensure_pubkey_on_aws_job_test.go
internal/models/pubkey_model.go

https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_KeyPairInfo.html talks about what to expect as fingerprint format, which is different then what we store in some cases.

fix(HMSPROV-390): calculate AWS fingerprint

---

api/openapi.gen.json
api/openapi.gen.yaml
go.mod
go.sum
internal/config/override_integration.go
internal/dao/pgx/reservation_pgx.go
internal/dao/tests/main_test.go
internal/dao/tests/noop_job_test.go
internal/dao/tests/reservation_test.go
internal/db/migrations/012_reservation_errors.sql
internal/jobs/common.go
internal/jobs/ensure_pubkey_on_aws_job.go
internal/jobs/noop_job.go
internal/jobs/queue/stub/memory_queue.go
internal/models/reservation_model.go
internal/payloads/error_payload.go
internal/payloads/reservation_payload.go
internal/services/aws_reservation_service.go
internal/services/noop_reservation_service.go
internal/services/noop_reservation_service_test.go

Because the job queue implementation is generic, there is no support for cancelling dependant jobs when some fail.
For this reason, jobs must explicitly check associated Reservation field Error for non-empty value using checkExistingError helper function. If it returns an error, the job MUST immediately exit prepending "step skipped: " to the error message.
This way, the actual error message will be prefixed by N prefixes for all remaining jobs in the queue. For example, for 3 jobs when the first fails it is: "step skipped: step skipped: actual error text".
The job code currently always finishes all dependant jobs, so 3 out of 3 jobs will be done. In other words, no matter if queue of dependant jobs will succeed or fail, the counter will be equal to number of steps.
The patch also adds a …

fix(HMSPROV-352): error out jobs early

---

internal/clients/http/image_builder/image_client.go
internal/clients/http/image_builder_errors.go

Images can be shared to different regions in Image Builder. 
shared images are not visible under /compose endpoint in IB but under /clone.
Therefore if an image is not visible under /compose,  before erroring out we should search for the image under /clone. 
Only if the image is not preset neither under compose nor clone we should error out with the message that the image is not available.

fix(HMSPROV-392): Check if image is an original or a shared one

---

deploy/clowdapp.yaml

The recent patch increased number of API and backend workers to 2. It is fine to test multiple workers, but for API workers it is inconvenient to have multiple workers on stage environment as you need to switch between k8s log consoles constantly.
This brings the number back to 1 but it keeps 2 workers.
@mshriver you mentioned some Splunk URL, do we have some Stage log monitoring database? I would love to have access to that.

chore: use one API worker

---

deploy/clowdapp.yaml

According to docs, minReplicas was deprecated, we should only use replicas field. Also there is no need to create ENV variables for these. The patch simplifies this.
Since I have tested that multiple backend workers work fine via Redis on stage, I am bringing the number back to 1 for everything. Looking up logs with multiple pods is a bad experience, we can increase this once we setup CloudWatch which is my priority for this sprint.

chore: simplify replica config and set all back to 1

---

internal/config/config.go
internal/config/validation.go
internal/services/aws_reservation_service.go
internal/services/gcp_reservation_service.go

Looks like everything is ready to enable cloudwatch API on stage, this is the only change that is needed to export logs via the API.
To get access to ELK/CW on AWS open the [HMSPROV-407](https://issues.redhat.com/browse/HMSPROV-407) ticket and follow the instructions to setup permissions for you account. You will need a GPG public key for a password to be emailed to you.
Testing: Not sure how to test this in ephemeral, but ideally let us merge this sometime in the morning hours so we can check stage. I am still waiting for my permissions to be approved.

fix(HMSPROV-407): enable cloudwatch in clowder

---

internal/config/helpers.go
internal/logging/zerolog.go

Turns out there is a typo in our codebase in `InProdClowder` so the variables were not printed correctly. This fixes it.

fix(HMSPROV-407): further improve logging of cw config

---

api/openapi.gen.json
api/openapi.gen.yaml
cmd/spec/main.go
cmd/spec/path.yaml
internal/clients/account_identity.go
internal/clients/http/ec2/ec2_client.go
internal/clients/interface.go
internal/clients/stubs/ec2_stub.go
internal/payloads/account_identity.go
internal/routes/all_routes.go
internal/services/account_identity.go

I'm unsure if this is the right approach, but opened the PR anyway to discuss.
---
Currently it's very easy for a mismatch between user hyperscaler accounts. Users need to make sure they shared the image with the same account they configured provisioning for.  To avoid this mismatch, image builder should offer to share the image with a source rather than asking for an account number, guaranteeing  that the image was shared with the correct account.

feat: add account identity endpoint

---

internal/config/config.go
internal/config/config_test.go
internal/config/helpers.go
internal/config/validation.go
internal/logging/zerolog.go

Turns out logic algebra can still bite. Also, I confirmed that the "cloudwatch type" clowder field is suppoed to be set to "app-interface" but it is actually blank. It's a known issue.
This patch should finally grab CW configuration from clowder and finally start logging. You cannot test this in ephemeral, this must be merged.

fix(HMSPROV-407): fix blank logic in cw initialization

---

cmd/pbmigrate/main.go

Turns out cloudwatch is not available for init containers on stage, so it panics. I was hoping to have migration logs in ELK stack for a longer time so we can investigate weeks after, well, not gonna happen!

fix(HMSPROV-407): disable cw for migrations

---

cmd/pbstatuser/main.go
internal/background/availability_queue_test.go
internal/kafka/interface.go
internal/kafka/interface_test.go
internal/kafka/kafka.go
internal/kafka/noop.go
internal/kafka/stub.go

Previously, if you started statuser it would start from offset 0 and process all the messages in the queue regardless of the offset start setting in the reader client.
Turns out that in Kafka, you have to set group name in order for the platform to "remember" the offset.
To test this, send some availability checks and then start statuser, it should NOT process any messages. Only when it is running it should be processing them.

fix(HMSPROV-387): set consumer group for statuser

---

internal/cache/mem_cache.go

Previously we used memory caching on stage, we now use Redis. It has its own statistics which we can utilize, no need to track Redis. And we only use the memory implementation to cache the app ID (single value), so this value was always zero.
This patch drops the metrics, it is not very useful now.

fix(HMSPROV-389): drop memcache count

---

cmd/pbstatuser/main.go
internal/background/availability_queue_test.go
internal/kafka/interface.go
internal/kafka/interface_test.go
internal/kafka/kafka.go
internal/kafka/noop.go
internal/kafka/stub.go

Last week, I enabled a Kafka consumer group which solved the problem of tracking offsets. While this worked fine locally, it does not on stage. I am not sure what is wrong, however, I figured out a different solution.
Statuser is only one instance at the moment, however, turns out that offsets can be also set based on time. When statuser is restarted, only newly created messages can be read. This patch does exactly that.

fix(HMSPROV-387): use time-based offset for statuser

---

deploy/testing.yaml

HMSPROV-411
This will be used to execute IQE within tekton pipelines in conjunction with the service deployment
This PR will precede the app-interface contributions that define the pipeline and trigger it. The file's inclusion will not trigger any automatic execution as-is during app deployment.
**Checklist**

ci(HMSPROV-411): Add testing.yaml for IQE CJI

---

internal/clients/http/sources/sources_client.go
internal/clients/http/sources/sources_client_test.go

The code assumSources respond for every source with only single authentication. This does not hold true as some Sources can have multiple applications defined.
But luckily authtype i sstable field and always holds provisionig-arn for Provisioning auth. This change makes use of this field and filters the Provisioning auth with certainit. It allows us to remove verification of Auth's Application as now we should be sure it's Provisioning.
Fixes HMSPROV-426

fix: filtering Provisioning auth for Source

---

internal/config/config.go

Image builder defines it's backend container as service not svc. This is fixing the typo for picking up that config.
Fixes HMSPROV-421

fix: image builder clowder config

---

deploy/clowdapp.yaml

We run migrations when api and worker pods start up, but not when statuser pod starts up. This should fix this.
It looks like during todays redeplyoment, k8s started redeployment with statuser first leading to booting up our app with old database.

chore: run migrations for statuser

---

cmd/pbstatuser/main.go
internal/clients/authentication.go
internal/clients/http/sources/sources_client.go
internal/kafka/source_result.go

The source's status is not being updated to "Available" or  "Unavailable" 
According to sources [integrate with us](https://consoledot.pages.redhat.com/docs/dev/services/sources/integration.html#_work_on_our_side) documentation the resource type is supposed to be "Application"

fix(HMSPROV-433): change resource type to application

---

internal/config/config.go

Common practice for unleash feature flags on ConsoleDot platform is to prefix the flag with the name of the app only, we initaly drafted the prefix to be `app.provisioning`, but to conform with the practice we should only have `provisioning`.

build: Change unleash prefix to only app name

---

internal/db/seeds/dev_small.sql
internal/services/aws_reservation_service.go
internal/services/gcp_reservation_service.go

Turns out that arguments must not be pointer because then the type assertion will fail when memory implementation is used:
https://github.com/RHEnVision/provisioning-backend/blob/main/internal/jobs/launch_instance_aws.go#L46-L50
For redis implementation it worked because gob decoder dereferences pointers.
Also added a missing padding in the dev seed script in another commit.
Both changes does not affect stage/prod it was a problem in local development mode (memory only job queue), therefore, I am not creating an issue.

chore: fix padding and job pointer to body

---

cmd/pbstatuser/main.go
internal/kafka/kafka.go

When I was searching in logs today I noticed that the statuser do not have account information for each log. Also it is missing any correlation id. So this patch adds that, also, when I was on that I also add source_id too so we can easily search for availability checks per source id.
In a separate patch, I noticed a typo in a variable name. Example log session:
```
9:25AM TRC Received message with key: 1, topic: platform.provisioning.internal.availability-check, offset: 0, partition: 0 binary=pbstatuser hostname=mone.home.lan payload="{\"source_id\":\"1\"}" version=HEAD
9:25AM TRC Getting authentication from source 1 account_number=6395343 binary=pbstatuser client=sources hostname=mone.home.lan org_id=13446659 source_id=1 trace_id=52fdfc072182654f163f5f0f9a621d72 version=HEAD
9:25AM WRN …
```

Improve logging statuser

---

internal/clients/http/azure/azure_client.go
internal/clients/http/azure/create_vm.go
internal/clients/http/azure/types/azure_types.go
internal/clients/interface.go
internal/clients/stubs/errors.go
internal/clients/stubs/sources_stub.go
internal/dao/dao_interfaces.go
internal/dao/pgx/reservation_pgx.go
internal/dao/stubs/context_getters.go
internal/dao/stubs/reservation_dao.go
internal/jobs/job_types.go
internal/jobs/launch_instance_azure.go
internal/migrations/sql/017_create_azure_reservation_details.sql
internal/models/reservation_model.go
internal/payloads/reservation_payload.go
internal/queue/jq/worker.go
internal/services/azure_reservation_service.go
internal/services/azure_reservation_service_test.go
internal/services/instance_types_service_test.go
internal/services/reservations_service.go
scripts/rest_examples/reservation-create-azure.http

Implements Azure client minimal version of CreateVM with most values staticly defined. Implements direct call from a service to the Azure client, which bypasses the job, which will need to be defined in followup.
Refs HMS-1058

feat: minimal PoC Azure implementation

---

cmd/pbstatuser/main.go
internal/logging/zerolog.go
internal/payloads/error_payload.go
pkg/worker/redis.go

During todays debugging session I noticed that when error happens, we do not print stacktrace. I added this to all error payloads (HTTP API pods) and worker pods. Not adding this to statuser where it is pretty obvious the codebase is small there.
Also refactored payload creation a bit, now it is a bit cleaner.

chore: add stacktrace to logging for API and worker

---

internal/clients/http/sources/sources_client.go
internal/logging/zerolog.go

Quick reminder - it is fine to silence linters at some times where it makes no sense. I find this one quite useful because I already forgot some case statements myself that could lead to dangerous code, but here it is not very useful.
Also my version of golint already warns about the out-of-package reassignment, it is okay as Zerolog library works this way.

chore: silence switch-case linter

---

deploy/clowdapp.yaml

This is a temporary workaround until we have secrets in place for all environments.

chore: enable passing Azure params

---

internal/clients/http/azure/azure_client.go
internal/clients/http/azure/create_vm.go
internal/clients/http/image_builder/image_client.go
internal/clients/http/image_builder_errors.go
internal/clients/interface.go
internal/clients/stubs/image_builder_stub.go
internal/payloads/error_payload.go
internal/services/azure_reservation_service.go
internal/services/azure_reservation_service_test.go
scripts/rest_examples/reservation-create-azure.http

Fetch Azure image name from image builder.
Unfortunatelly IB provides only the Name and nID.
Thus we are composing the ID manually on our side.
Fixes HMS-1219

feat: Fetch Azure image name from image builder

---

README.md
internal/clients/http/image_builder/image_client.go
internal/clients/http/sources/sources_client.go
internal/ctxval/edge_id.go
internal/ctxval/keys.go
internal/headers/headers.go
internal/middleware/logger.go
internal/middleware/trace_id.go

This adds edge request id from headers into logs. This should be according to folks on the forum slack channel the best request id to log along for correlation with the edge API.
Also adds documentation link to the README.

chore: add edge request id into logger

---

internal/dao/pgx/reservation_pgx.go
internal/dao/tests/reservation_test.go

This fixes a regression introduced by Azure refactoring: https://github.com/RHEnVision/provisioning-backend/commit/02b55c39af439a06db029ec0fb7a02a1286406c4
The step_titles column somehow dropped from the code, I assume you had the branch from earlier than it was introduced.
This is a regression. QA scenario:
* Create an AWS reservation.
* Get reservation details through `reservations/aws/ID` (not `reservations/ID` that returns only basic data)
* Check if it contains all the generic fields (success, status, steps, step_titles...)
* Check if it contains all the AWS fields (instance id, amount, instance type...)

fix(HMS-1240): add step titles back

---

api/openapi.gen.json
api/openapi.gen.yaml
cmd/spec/main.go
cmd/spec/path.yaml
cmd/typesctl/providers/ec2_types.go
internal/clients/http/ec2/ec2_client.go
internal/clients/interface.go
internal/clients/launch_template.go
internal/clients/stubs/ec2_stub.go
internal/jobs/launch_instance_aws.go
internal/models/reservation_model.go
internal/payloads/launch_template_payload.go
internal/payloads/reservation_payload.go
internal/routes/all_routes.go
internal/services/aws_reservation_service.go
internal/services/instance_types_service.go
internal/services/launch_templates_service.go
internal/services/reservations_service.go
scripts/rest_examples/http-client.env.json
scripts/rest_examples/launchtemplates-aws-list.http
scripts/rest_examples/reservation-create-aws.http
scripts/rest_examples/reservation-create-azure.http
scripts/rest_examples/reservation-create-gcp.http
scripts/rest_examples/reservation-get-1-aws.http

This patch introduces new client type:
```go
package clients
// LaunchTemplate represents a generic launch template for a hyperscaler.
type LaunchTemplate struct {
// ID is an identifier, for example "lt-94397398248932342" for AWS EC2.
ID string
// Name describes the launch template, user defined.
Name string
}
```
I am aiming to have a generic LaunchTemplate, the terminology we use for generic types is AWS EC2. I am assuming other hyperscalers have similar templating, well, except Azure where it is JSON. There is a new endpoint and OpenAPI spec update which lists those. The UI is supposed to load this once region is selected since region is required URL parameter (or error). The ID field must be then provided as a new field "LaunchTemplateID" in an AWS reservation detail or set to blank …

Support for AWS Launch Templates

---

cmd/pbapi/main.go
cmd/pbstatuser/main.go
cmd/pbworker/main.go
internal/background/initialize.go
internal/background/queue_metrics.go
internal/metrics/metrics.go
internal/random/random.go
pkg/worker/job.go
pkg/worker/redis.go

This patch updates the job queue size metric and adds new metric that represents in-flight tasks: number of tasks which are currently in processing. Note that while job queue size is a global value (Gauge) - this is actually a redis queue length, the in-flight number is different for each consumer/worker (GaugeVec, vectorized by worker unique hostname).
For monitoring and alerts, we are interested in the following:
* Job queue size (one number). When it hits > 1000 we should alert that workers are too slow picking up new jobs (not running for example).
* In-flight count (sum). When the sum is > 500 we should alert that workers are probably too busy (can hit CPU/memory limits at some point).
I am making these numbers up these are educated guesses, feel free to tune them up. We have 3 …

Update job queue metrics

---

api/openapi.gen.json
api/openapi.gen.yaml
cmd/spec/path.yaml
internal/dao/dao_transaction.go
internal/dao/pgx/reservation_pgx.go
internal/payloads/reservation_payload.go
internal/services/aws_reservation_service.go

I propose to insist on pubkeys even when launch templates are required. We have foreign keys and we would need to introduce NULLs and do OUTER JOINs just for this small use case. For now I think this should be reasonable approach.
So this patch changes nothing effectively, but documents this in the OpenAPI spec.
While working on this, I noticed that the transaction code tries to commit after rollback which is leading to incorrect error - the original root cause is thrown away and "cannot commit: transaction is closed" is returned to the client. This fixes it.

fix(HMS-1260): document pubkey and template behavior

---

internal/metrics/metrics.go

Default prometheus buckets are in seconds:
var DefBuckets = []float64{.005, .01, .025, .05, .1, .25, .5, 1, 2.5, 5, 10}
However our metric is in ms, therefore we need to define buckets in ms too in order to get any reasonable numbers from this metric. This patch fixes that.

fix(HMS-1259): update avail check buckets to ms

---

CONTRIBUTING.md

Since the HMSPROV commits are failing and the link to Jira is outdated, we might want to update the docs.

docs: Update HMSPROV to HMS

---

cmd/pbapi/main.go
cmd/pbstatuser/main.go
cmd/pbworker/main.go
internal/kafka/source_result.go
internal/metrics/metrics.go
pkg/worker/job.go
pkg/worker/redis.go

This adds a new duration metric which captures duration of every job processed from the background redis queue. It contains "type" label which is the job name, e.g. `launch_instances_aws` for AWS EC2 launch job. Since this is the first metric we have in workers, the patch adds a new prometheus endpoint in the main function.

fix(HMS-879): workers metrics

---

internal/clients/http/azure/create_vm.go
scripts/rest_examples/reservation-create-azure.http

We were forcing a disk name, we can just leave disk name blank and it will be named with the VM name prefix and randomized suffix.
Refs HMS-1146

fix: allow dynamic naming for Azure disk, IP and NIC

---

cmd/pbapi/main.go
cmd/pbstatuser/main.go
cmd/pbworker/main.go
internal/background/initialize.go
internal/config/config.go
internal/logging/zerolog.go

Pulls initialization in a single function, `InitializeStdout` is used just in tests, where we know we need only stdout logger.

Logger initialization refactor

---

build/RedHat.dockerfile
build/Upstream.dockerfile
go.mod

Use static version for go build container.
We want to migrate to new versions consciously.
OTH we want to use the latest ubi version for the final container.

build: Use static go build version

---

mk/tools.mk

Update of the make install-tools to work for our required version of Go.

chore: Update Makefile to work for Go 1.18

---

internal/clients/http/azure/create_vm.go

Many resources are created faster then the default 30 second interval. This makes in the worst case the whole proces up to 30 times # of resources slower.
We want to shorten this inter
Fixes HMS-1404

feat: shorten Azure polling intervals

---

internal/migrations/sql/018_delete_cascade_azure.sql
scripts/rest_examples/reservation-get-1-azure.http

This is what we do for other providers.
We loose all the details about the reservation.
Fixes HMS-1402

fix: cascade delete of pubkey to Azure details

---

internal/services/aws_reservation_service_test.go
internal/services/azure_reservation_service_test.go
internal/services/gcp_reservation_service_test.go

Adding a test for each provider's reservation checking we are failing the test if the region/zone/location provided are not supported.

refactor: Add test for valid region/zone/location

---

config/api.env.example
deploy/clowdapp.yaml
docs/configure-azure.md
docs/lighthouse.tmpl.json
internal/clients/azure_offering_template.go
internal/clients/http/azure/lighthouse.tmpl.json
internal/config/config.go
internal/routes/all_routes.go
internal/services/azure_offering_template_service.go
internal/services/azure_offering_template_service_test.go

Might not be ideal solution to the problem , I feel it being bit nasty, but it gives us quite some benefits:
- We are testing the template we use in documentation, cool :tada:
- We can't forget change the tenant in template, because it's dynamic
- We can change the template in code. Cool.
Happy to hear improvements on the technical solution tho :)
I would whole heartedly agree it has quite some quirks :stuck_out_tongue: 
-----
Adds lighthouse offering template rendering.
This makes the template available on a public URL.
Reuses the documentation template.
Also improves the documentation of Why in the Azure devel doc.
Refs HMS-1148
-----
Add lighthouse template to the container image during build.
Fixes the build container on 1.18 tag
Adds latest to ubi-minimal

feat: Azure lighthouse offering template

---

deploy/clowdapp.yaml

Since we are playing around with pod counts and limits, I would like to experiment a bit more. I was told that the limits are currently.
```
$ oc get quota compute-resources-non-terminating -o json | jq ".status"
{
"hard": {
"limits.cpu": "6",
"limits.memory": "24Gi",
"requests.cpu": "3",
"requests.memory": "12Gi"
},
"used": {
"limits.cpu": "6",
"limits.memory": "6Gi",
"requests.cpu": "600m",
"requests.memory": "600Mi"
}
}
```
In our configuration, we are requesting limit quota of 1000m (full CPU) with 100m increment per pod. I think that is a bit overkill for our use case and that is why we are hitting the hard limit: 3+3+1 = 7 CPUs (7000m). If I half the hard limit that is actually 3500m so we still have some room to grow in terms of amount of pods.
Memory wise, I think we are good. So …

chore: limit cpu and use 3-3-1

---

deploy/clowdapp.yaml

I _think_ added annotation to a wrong type, this should fix this.
Hopefully this fixes deployments.

chore: remove linter annotation

---

config/api.env.example
internal/clients/http/gcp/gcp_client.go
internal/clients/http/gcp/gcp_errors.go
internal/clients/interface.go
internal/clients/stubs/gcp_stub.go
internal/config/config.go
internal/jobs/launch_instance_gcp.go
scripts/rest_examples/reservation-create-gcp.http

After an investigation, I have not found a better way to fetch the information of the instances created under a single reservation. 
This PR: 
- Generates a uuid for each bulkInsert request and  will be used as a label
-  Fetches the created instances corresponding to bulkInsert requests' uuid 
-  saves the instances ids in the db and also share them under GetGCPByID
**Things I would like to get feedback on:** 
- Does the usage of uuid make sense like that? 
-  Did I use otel correctly and did not miss something?

feat(HMS-1001): Add created instances ids to GCP reservation

---

internal/ctxval/copy.go
internal/jobs/common.go
internal/metrics/metrics.go
internal/metrics/registration.go
pkg/worker/redis.go

I noticed that the existing reservation job metrics are missing the prefix.
Also we need to track success and failure rate of jobs/reservations. This cannot be done on the job level as background jobs do not have any sort of error handling, this must be all done on the reservation level when we finish reservation either with error or success flag.
This PR adds a new metric which I will use on the dashboard for the main SLO.

fix(HMS-1105): add reservation counters

---

deploy/Provisioning-1674548289785.json
internal/metrics/metrics.go

This is a big update of the jobs/reservations panes on our dashboard. Now it shows proper numbers even when there is no data, I learned this from IB team and the trick is to use `on() vector(0)`.
But the big new feature is (also learned from IB dashboard) a new variable called Hyperscaler where you can switch between azure, aws and gcp to drill down the data. Hard to show on an image so here is a short demo:
https://www.youtube.com/watch?v=X7M7WxkBLHc

fix(HMS-1105): improve reservations dashboard

---

internal/metrics/metrics.go

The dashboard now shows 59 minutes p99 time for jobs, well, because we still measure this in milliseconds instead of seconds. This fixes it. Numbers will be off for few days I guess :-) Sorry!

fix(HMS-1105): measure jobs in seconds

---

cmd/pbstatuser/main.go
internal/clients/http/azure/create_vm.go
internal/clients/http/ec2/ec2_client.go
internal/clients/http/gcp/gcp_client.go
internal/clients/http/image_builder/image_client.go
internal/clients/http/sources/sources_client.go
internal/config/flags_listener.go
internal/dao/dao_transaction.go
internal/jobs/common.go
internal/jobs/launch_instance_aws.go
internal/jobs/launch_instance_azure.go
internal/jobs/launch_instance_gcp.go
internal/jobs/noop_job.go
internal/kafka/kafka.go
internal/middleware/account.go
internal/migrations/migrations.go
internal/models/pubkey_model.go
internal/payloads/error_payload.go
internal/services/error_renderer.go
internal/services/pubkey_service.go
pkg/worker/redis.go

Heads up: Please do not include error message in log message body, because it leads to unique messages like _cannot assume role operation error STS: AssumeRole, https response error StatusCode: 403, RequestID: 47e5734c-a37e-4be3-aba2-77f4e306a055_ which are incorrectly identified as unique errors by Sentry and creates too many error reports with the same cause.
The code which is causing this is:
logger.Error().Err(err).Msgf("cannot assume role %s", err)
The correct way is:
logger.Error().Err(err).Msg("Cannot assume role")
Note the error itself actually goes into logger through Err function, there is no need to copy it again. This is counter intuitive because when wrapping errors, you do exactly the opposite: fmt.Errorf("cannot assume role %w", err)

chore: avoid logging Err().Msgf("msg with error")

---

internal/clients/http/azure/create_vm.go
internal/clients/http/azure/create_vms.go
internal/clients/instance_params.go
internal/clients/interface.go
internal/clients/stubs/azure_stub.go
internal/dao/stubs/context_getters.go
internal/dao/stubs/reservation_dao.go
internal/jobs/launch_instance_azure.go
internal/jobs/launch_instance_azure_test.go
scripts/rest_examples/reservation-create-azure.http

Splits Azure launch start and polling for status.
Now we start the launch process for all instances first, only then we start polling for the creation result.
Fixes HMS-1407

feat: Create Azure VMs in paralel

---

deploy/clowdapp.yaml

I've adjusted the names on the last rebase, but forgot to adjust the clowdapp as well.

build: fix the Azure env variable names

---

internal/cache/metrics_decorator.go
internal/metrics/metrics.go
internal/metrics/registration.go

SSIA this was created before we introduced the package. Also, all our metrics starts with `provisioning_` prefix. I would like to put these into our dashboard as well once I implement RBAC cache and miss metrics.

Refactor cache metrics

---

deploy/testing-integration.yaml

HMS-103
This new CJI template will run end-to-end tests after the post-deploy tests in testing.yaml have run.
(A new testing deployment will need to be added to app-interface before this new template has any effect.)
**Checklist**

 ci(HMS-103): Add testing-integration.yaml for stage post-deploy integration testing

---

internal/payloads/permissions_payload.go
internal/services/aws_iam_service.go
scripts/rest_examples/source-1-permission_check.http

When region was not provided, the code was missing a `return` statement which led to incorrect output.
This patch fixes this, instead returning an error, we can use the default region which we have in the configuration. It should ber set to the closest region which is often the fastest.
Also the payload was missing JSON tags, Chi renderer likely uses reflection to pick that up but it makes sense to have it defined correctly.

fix(HMS-1110): use default region for perm check

---

deploy/testing-integration.yaml

These e2e stage post-deploy UI tests need to use a Job instead of ClowdJobInvocation, as the testing environment does not have Clowder access.
***
**Checklist**

ci(HMS-103): Update testing-integration.yaml to use Job instead of CJI

---

internal/middleware/trace_id.go

This adds correlation (trace) id in all response headers. This is useful when debugging success (or looks like success) requests on stage, the header immediately gives something you can search in Kibana.
Although we use trace id from open telemetry, this is not the official header which is [much more complex](https://www.w3.org/TR/trace-context/) and also does not make sense in response headers.
Edit: Initially I used `Correlation-Id` but I think we should stick to what we actually store in logs.

chore: add trace id response header

---

internal/clients/http/image_builder/image_client.go
internal/models/reservation_model.go
internal/services/azure_reservation_service.go
internal/services/azure_reservation_service_test.go
scripts/rest_examples/http-client.env.json
scripts/rest_examples/reservation-create-azure.http

Azure image IB ID check had a typo in the if statement, so it was actually never performed. I realized that when I started testing Azure on my dev setup and wanted to spawn a RHEL generic image from the Azure marketplace.
The patch also updates the http testing file with more sane defaults including the RHEL, btw image IDs are here: https://imagedirectory.cloud/browser/Azure (searching is not yet possible).

fix: Azure image check

---

internal/clients/http/image_builder/image_client.go
internal/models/reservation_model.go
internal/services/gcp_reservation_service.go
scripts/rest_examples/reservation-create-gcp.http

This allows to launch official images not just UUIDs from image builder. Comes with an example .http file update which defaults to RHEL9 official image: https://imagedirectory.cloud/browser/GCP

chore: allow non-IB images for GCP

---

internal/logging/sentry.go
internal/logging/sentry_replacer.go
internal/logging/sentry_replacer_test.go

It looks like AWS SDK does not makes use of error wrapping, we already workaround that in `isAWSOperationError` function. However, errors like `unable to initialize AWS client: cannot assume role operation error STS: AssumeRole, https response error StatusCode: 403, RequestID: 23c69a5e-69bf-439a-a1c5-c2161ce06a8e, api error AccessDenied: User: arn:aws:iam::12333232:user/crc-ephemeral is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::321321213:role/satellite-services-role` makes Sentry to identify these as unique errors.
This patch adds regular expression writer filter that filters out UUIDs and ARNs so errors are no unique by the error message. This will hopefully group up errors in Sentry.

chore: introduce Sentry replacer

---

deploy/Provisioning-1674548289785.json
deploy/dashboards/grafana-dashboard-provisioning.configmap.yaml

I took a closer look on our SLO target (200ms successful requests) and because it way way bellow 95% I investigated, looks like the query we have there is not correct. Also took the opportunity to slightly enhance all other HTTP-related panels:
* Removed HTTP Success Latency graph and created a new one named HTTP Success Latency 200ms Target which is now the "big number" with background line graph for history.
* The expression `sum(rate(provisioning_http_request_duration_ms_bucket{code=~"2.*", le="200"}[$__range])) / sum(rate(provisioning_http_request_duration_ms_count[$__range]))` does divide by all requests, but we need to divide only by successful counts. This was giving us quite low number under our current SLO (95%). The correct expression is …

chore: update http dashboard panels

---

internal/services/pubkey_service.go
pkg/worker/redis.go

I did a full review of all our Sentry errors, I noticed one that is ugly when pubkey is not valid (name/body), this fixes it returning a better error.
Also when there is a panic in worker, I saw nil exception this hopefully fixes it.

chore: improve glitchtip error handling

---

config/api.env.example
deploy/clowdapp.yaml
internal/config/config.go
internal/routes/all_routes.go

We have figured out that compression for browsers are done by 3scale, there is no point having this feature for in-cluster queries. Removing.

refactor: remove compression

---

internal/clients/http/azure/create_vm.go
internal/clients/http/image_builder/image_client.go
internal/clients/http/image_builder_errors.go
internal/clients/instance_params.go
internal/clients/interface.go
internal/clients/stubs/image_builder_stub.go
internal/jobs/launch_instance_azure.go
internal/services/azure_reservation_service.go
internal/services/azure_reservation_service_test.go

Support for fetching resource group the image resides in from Image Builder.
This allows for launching images that are build in a different resource group then the Launch one.
Changes the expected identifier in the Azure client.
Now we expect the full ID instead of a name, thus the resolution of name to ID is done in the service now.
Fixes HMS-1691
This was enabled by https://github.com/osbuild/image-builder/pull/707
We need to wait for IB to release for us to release this.

feat: Fetch Azure image resource group from IB

---

cmd/pbapi/main.go
internal/ctxval/correlation_id.go
internal/ctxval/keys.go
internal/middleware/correlation_id.go
internal/middleware/logger.go

After adding the correlation id header to the request sent from the UI, we add the correlation id to the context and the logger in this PR.

feat(HMSPROV-449): Add correlation id to logger and context

---

.editorconfig

JetBrains Fleet does spaces by default. This should fix it.

chore: use tabs for mk files

---

.github/workflows/gotest.yml

We use a GHA OpenAPI generation but then we call `make validate` to generate the same files. The use of the GHA is not needed actually.
In fact, it started failing our tests with a weird error recently:
```
Error:  Check the spelling of the generator's name and try again.
202
Error: Process completed with exit code 1.
```
This patch removes that, the `make` utility does perform generation and then `git diff` to check if there is any sort of change. This is all we need.

build: drop GHA OpenAPI validation

---

deploy/Provisioning-1674548289785.json
deploy/dashboards/grafana-dashboard-provisioning.configmap.yaml

SSIA
Also changed the defaults to 1h window last 24 hours which is a bit more relevant I think. Also faster.
The version dropped from 7 to 1 not sure why, I exported this via Grafana, I guess it is just informative number since it is managed by app-interface rather than Grafana's built-in versioning: https://grafana.com/docs/grafana/latest/dashboards/build-dashboards/manage-version-history/

chore: update dashboard SLO latency to 500ms target

---

.golangci.yml
internal/cache/redis_cache.go

The account cache currently use JSON encoding, but the newer version of the linter revealed that we removed JSON tags from models. Cache works, however, the linter error is still correct and I would like to keep this lint warning on.
Instead of adding JSON tags to models, I would like to change behavior of the cache, instead of JSON let’s use Gob (native Go binary encoding) which is not only faster, but it also does not require any tags. Redis is not very transparent and we unlikely need to investigate contents of cache (logging can do the same job if we need to).
The patch changes to Gob encoding, only account is currently stored in cache as a struct. Upgrade path: automatic. When previous cache entry is loaded, Gob decoding fails and NotFound error is returned thus the cache entry is …

refactor: use Gob encoding for cache

---

cmd/pbapi/main.go
go.mod
go.sum
internal/config/helpers.go

We currently leave the GOMACPROC set to default which is amount of cores + 1. In Kubernetes this is actually 3 which might be little too little. There is a library that tries to heuristically find the sweet spot. It also dumps the value to logs.
https://github.com/uber-go/automaxprocs

fix(HMS-1784): set GOMAXPROC for API workers

---

config/api.env.example
internal/config/config.go
internal/queue/jq/worker.go
pkg/worker/redis.go

Jobqueue concurrency was uncapped until now, this was a bug. I meant to cap it at 64 per pod, however, the setting was only for pollers which spawn new goroutine on each job received.
This patch removes processing in goroutines per job, every poller executes jobs in the same goroutine which leads to effective concurrency that can be capped by `WORKER_CONCURRENCY` variable (previously maxPollers which was confusing I think).
The default value is set to 33, the idea is that with 3 pods we are at concurrency of 100 (99 actually) which is easy to do math on. For example, AWS bucket for instance launch is 1000 so at "maximum speed" the service can withstand 100 seconds without throttling. We can update the number as we get access to CloudWatch AWS API logs and learn how we can scale the …

fix(HMS-1782): cap job concurrency at 100

---

.github/workflows/gotest.yml

I noticed that we do run `make validate` which is supposed to generate clients and then validate them. All targets are phony, except `generate-clients` which by default does not do anything since there is no change in the code base.
This patch adds the required `touch` call which causes the clients to be actually regenerated, then `git` is used to compare for changes. Since the OpenAPI generator version if pinned, it should not result in any difference. The tools must be installed from now on, it was working without them because actually nothing was happening.
In addition to that, the `bin` directory is cached so `go install-tools` will be only executed when necessary speeding up the validation.
In a separate commit, I upgraded GHA `setup-go@v4` to version 4 which automatically cache …

build: install go tools and cache

---

.github/workflows/gotest.yml
mk/code.mk

CI currently fails with
```
/usr/bin/tar -xf /home/runner/work/_temp/9d82feee-0932-4ee7-82bf-2f8f8b676785/cache.tgz -P -C /home/runner/work/provisioning-backend/provisioning-backend -z
/usr/bin/tar: ../../../go/pkg/mod/go.opentelemetry.io/otel@v1.14.0/VERSIONING.md: Cannot open: File exists
Error: /usr/bin/tar: ../../../go/pkg/mod/go.opentelemetry.io/otel@v1.14.0/propagation/trace_context_test.go: Cannot open: File exists
```
This is because cache is stored twice, Go cache and Linter cache. The documentation for the linter explicitly disables the Go cache because it is essentially stored twice. This patch does exactly that.
During editing of the workflow I realized that we do not build the artifacts at all. So there can be a build error in `main.go` and we would not notice until container …

build: disable cache for golangci-lint

---

go.mod
go.sum
mk/deps.mk

I forgot to do it during the bump.

build: bump Go version in go.mod to 1.19

---

internal/logging/sentry_replacer.go
internal/logging/sentry_replacer_test.go

Solves sentry error:
```
:read tcp 10.128.24.14:42094->10.0.217.126:6379: i/o timeout
Module "github.com/RHEnVision/provisioning-backend/pkg/worker", line 183, in (*RedisWorker).fetchJob
Module "github.com/RHEnVision/provisioning-backend/pkg/worker", line 154, in (*RedisWorker).dequeueLoop
```

chore: replace IPv4 for i/o timeout errors

---

internal/cache/redis.go
internal/services/sources_service.go

The provider field was hardcoded to "azure" for some reason. I noticed this today.
```
{"provider":"azure","aws":{"account_id":"399777895069"},"azure":null}
```

fix(HMS-1800): fix a typo in upload info

---

api/openapi.gen.json
api/openapi.gen.yaml
cmd/spec/example_other.go
cmd/spec/example_source.go
cmd/spec/example_templates.go
cmd/spec/example_types.go
cmd/spec/main.go
cmd/spec/path.yaml
internal/clients/http/sources/sources_client.go
internal/clients/http/sources/sources_client_test.go
internal/clients/interface.go
internal/clients/launch_template.go
internal/clients/source.go
internal/clients/stubs/sources_stub.go
internal/payloads/instance_types_payload.go
internal/payloads/launch_template_payload.go
internal/payloads/sources_payload.go
internal/services/azure_reservation_service_test.go
internal/services/gcp_reservation_service_test.go
internal/services/sources_service_test.go

Continuation of https://github.com/RHEnVision/provisioning-backend/pull/500 for all sources endpoints. I am keeping the deprecated endpoints untouched for now, let’s remove them in a separate PR.
I cannot continue working on upload_info until https://github.com/RHEnVision/provisioning-backend/pull/534 is merged tho, so that is TBD.

fix(HMS-1616): OpenAPI cleanup and examples

---

.gitignore
build/RedHat.dockerfile
build/Upstream.dockerfile
cmd/pbackend/api.go
cmd/pbackend/main.go
cmd/pbackend/migrate.go
cmd/pbackend/statuser.go
cmd/pbackend/worker.go
deploy/clowdapp.yaml
internal/config/config.go
internal/config/helpers.go
internal/version/version.go
mk/compile.mk

We build four different binary files: pbapi, pbworker, pbstatuser and pbmigrate. Each about 70MiB in size, we copy them into the container. The most of the size comes with libraries (dependencies), if we only could ship just one binary.
This patch introduces a new binary called `pbackend` which replaces all of the four saving 70% of the old size and trimming compilation time in half (without Go cache). It takes an argument which means which program to start:
```
[lzap@nuc provisioning-backend]$ ./pbackend 
Usage: pbackend [migrate|api|worker|statuser|version]
[lzap@nuc provisioning-backend]$ ./pbackend version
Version 4f2e, Go version go1.19.6, built 2023-05-23T13:09:37Z
[lzap@nuc provisioning-backend]$ ./pbackend migrate
...migrates database...
```
This patch is changing container …

build: use single binary

---

mk/code.mk

Looks like I misread how golangci-lint handles GOROOT, I thought it would use that variable but looks like it always tries to detect the GOROOT via `go env GOROOT`. Problem is, it uses system Go rather than the specific Go version we want.
https://github.com/golangci/golangci-lint/blob/master/pkg/goutil/env.go
This patch adds PATH for the linter command, so the `go` command resolves to the proper version, this fixes the problem.

build: use PATH for golint

---

internal/dao/dao_interfaces.go
internal/dao/pgx/account_pgx.go
internal/dao/stubs/account_dao.go
internal/dao/tests/account_test.go

We made a conscious decision not to use transactions when creating accounts because it would be too slow. There are cases when user that don’t have account created in our database yet comes and performs operation that does many requests, this can lead to this error.
We now saw this once in production, so let’s fix this. Instead of using transactions, which are slow, this patch uses "UPSERT" technique which in Postgres is available through "ON CONFLICT". Here is when not having ORM is a really powerful.
I think we should open up discussion if we can remove account_number from the database. Handling of empty/null values is extra work and it makes the query more complex than it needs to be.

fix(HMS-1830): improve concurrency of account creation

---

deploy/clowdapp.yaml

Adds GCP env variable from credentials in k8s
I think the JSON should be enough in prod environments, as `GCP_PROJECT_ID` is consumed only in the service client, but not the customer client, but could you give me a sanity check here @adiabramovitch pls? :)

build: route GCP secrets to ENV

---

deploy/Provisioning-1674548289785.json
deploy/dashboards/grafana-dashboard-provisioning.configmap.yaml
internal/metrics/metrics.go

We increased it to 5000ms for Summit but now that we have pushed to prod and new buckets include 750, 1000 and 2000ms we can lower it back.
I propose 750ms it has been 100% for last 24 hours. I will raise app-interface change once this is merged.

chore: change SLO on the dashboard back

---

.gitignore
deploy/clowdapp.yaml

This patch adds a new column called "template" which is a boolean with the meaning if a Launch Template was used during operation.
It also adds Azure data to the same template merging data into single dataset. A new column called "provider" with either "aws" or "azure" values was added so we can perform some common statistics on top of all providers. Note that those providers have different regions/locations and instance types and since the terminology and our database fields differ, I propose to simply use the current column names which come from AWS terminology.
In addition, the "template" is currently always "false" as Azure not yet support Launch Templates.
Example output:
| provider | created\_at | finished\_at | success | account\_number | org\_id | source\_id | type | region | …

chore: add azure and templates to floorist

---

internal/clients/errors.go
internal/clients/http/sources/sources_client.go
internal/clients/http/sources/sources_client_test.go
internal/clients/http/sources_errors.go
internal/models/model_constants.go

Using sources filtering instead of fetching all the authentications and sources and for the filtering in our backend. 
Few things: 
1. Some of the tests became meaningless because the data we mock  (from sources) is already filtered so there is no need in checking the cases like: 
- a source of a type different than "Application" 
-  checking the filtering of sources by a provider 
2. Regarding the mapping between our source types (aws, gcp, azure) and sources source types (amazon, google, azure) I am not sure there is a better way to do the mapping. I wanted to rely on their API but I think it gets messy and either way, our service will break if there will be a change in their API (please correct me If I am wrong)
Not sure what is the best solution here, maybe you will have something :)

fix(HMSPROV-451): Use sources filtering mechanism

---

mk/0_initial.mk

When you have GOROOT set in your profile, the makefile would use it instead of wanted GOROOT from the Go 1.19.6 (the current version), this fails the linter because it would use Go version which was set by environmental variable.
We don’t want that, this change will override any previous GOROOT setting from the environment so the proper Go version is ensured.

chore: do not allow override of GOROOT

---

internal/clients/http/gcp/gcp_client.go
internal/clients/instance_params.go
internal/clients/interface.go
internal/clients/stubs/gcp_stub.go
internal/jobs/launch_instance_gcp.go
internal/models/reservation_model.go
internal/payloads/reservation_payload.go
internal/services/gcp_reservation_service.go
internal/services/launch_templates_service.go
scripts/rest_examples/launchtemlates-gcp-list.http
scripts/rest_examples/reservation-create-gcp.http

Adding support for listing launch templates in GCP and launching instances from a specific template name. 
GCP works with launch template names rather than launch template IDs.

feat(HMS-1828): Add listing templates and creating instances from a template

---

internal/clients/errors.go
internal/clients/http/image_builder/image_client.go
internal/clients/http/sources_errors.go
internal/payloads/error_payload.go
internal/payloads/error_payload_test.go
internal/services/aws_reservation_service.go

We need to return 400 not 500 on invalid compose ID.
Also refactors error handling a bit, it is now more generic and straightforward.

fix(HMS-1884): return 400 on invalid compose ID

---

pkg/worker/redis.go

I would like to know when a job expired to be able to easily find it by job id. This will create an error log entry and also sentry error so we can track these easily.

chore: log job cancellation to error level (Glitchtip)

---

api/openapi.gen.json
api/openapi.gen.yaml
internal/clients/source_upload_info.go
internal/payloads/sources_payload.go
internal/services/sources_service.go

For the complete workflow to work from the UI the upload info logic was missing. 
In this PR:
- we are fetching the I am policy from the customer project,
- filtering to get the provisioning service account principal in order to pass into the UI
In the front, we have a validation that the principal we have fetched is equal to the email/principal that was shared with the image.

feat(HMS-1932): Add gcp source upload info

---

pkg/worker/redis.go

It appears that we log "Job cancelled" each time a job finishes. Even for successful jobs. This fixes it.

chore: improve job timeout logging

---

cmd/pbackend/api.go
cmd/pbackend/statuser.go
cmd/pbackend/worker.go
config/api.env.example
deploy/clowdapp.yaml
docs/dev-environment.md
internal/config/config.go
internal/jobs/common.go
internal/jobs/launch_instance_aws.go
internal/jobs/launch_instance_azure.go
internal/jobs/launch_instance_gcp.go
internal/jobs/noop_job.go
internal/kafka/notification_msg.go
internal/kafka/topics.go
internal/notifications/interface.go
internal/notifications/noop.go
internal/notifications/notifications.go
scripts/kafka.start.sh
scripts/rest_examples/send-notification.http

This PR adds notification support, and sends a  message via kafka once launch process is finished.
We currently support two event types under Image builder application:
- Launch completed
- Launch failed
**EDIT:
In order to test locally, follow the README.notifications** 
In order to test it under stage env:
1. Go to Notifications -> Integreation 
2.  create a new webhook integration, you can use https://webhook.site/ tool that will provide a unique webhook URL
3. Go to Notifications -> RHEL
4. Create a new behaiver group, assign one of the above event types (i.e `Launch failed`) and the integration you have created.
Please note that only webhooks work ATM,  email templates will be added later.

feat(HMS-1550): add notifications service integration

---

cmd/pbackend/main.go
cmd/pbackend/stats.go
cmd/pbackend/statuser.go
config/api.env.example
deploy/clowdapp.yaml
internal/background/db_stats.go
internal/background/initialize.go
internal/config/config.go
internal/dao/dao_interfaces.go
internal/dao/pgx/stat_pgx.go
internal/metrics/metrics.go
internal/metrics/registration.go
internal/models/statistics.go

Numbers are pretty much unusable for the next 24 hours after deployment. On stage, this is almost every day, on prod this skews the numbers.
Let’s calculate these numbers properly via a background job on regular intervals and export those values as prometheus gauges.
This patch adds database connection and a goroutine to the statuser (which we only have single instance of) which performs two DB queries in every 30 minutes and updates prometheus gauges with the numbers. It will allow us to see:
* Number of success/failed launches per hyperscaler in the last 24 hours
* Number of success/failed launches per hyperscaler in the last 28 days
* Duration of the statistics routine (just in case it gets slower in the future)

fix(HMS-2002): proper launch statistics

---

internal/metrics/metrics.go

SSIA this was introduced yesterday by 
https://github.com/RHEnVision/provisioning-backend/pull/574
But quite frankly, I just want to see redeployment. I don’t see the new stats pod yet for some reason, the pipeline is green tho.

chore: update some metric labels

---

deploy/clowdapp.yaml

I messed up memory limits. CPUs mili-units are "m" but for memiry MiBs are "Mi". Stage is currently no deploying anything, this should fix it. The error was:
`error updating resource Deployment provisioning-backend-worker: Deployment.apps "provisioning-backend-worker" is invalid: [spec.template.spec.containers[0].resources.requests: Invalid value: "100Mi": must be less than or equal to memory limit, spec.template.spec.initContainers[0].resources.requests: Invalid value: "100Mi": must be less than or equal to memory limit]`
This patch also sorts the environment variables to a meaningful order:
* requests.cpu - 700m - 3000m
* requests.memory - 700Mi - 12Gi
* limits.cpu - 3500m - 6000m
* limits.memory - 7Gi - 24Gi
This list also shows our current limits/requests and the cap set by the …

fix(HMS-2002): fix memory request limits

---

deploy/testing.yaml

In preparation for adding prod post-deploy tests, this PR parameterizes the post-deploy test template to support both stage and prod environments. Currently the only parameters are the dynaconf environment and the pytest marker expression used by pytest to determine both the environment and the tests to run against it.
*** …

ci(HMS-1947): Parameterize post-deploy tests for both stage and prod

---

deploy/Provisioning-1674548289785.json
deploy/dashboards/grafana-dashboard-provisioning.configmap.yaml

Dashboard change which introduces the newly calculated metrics for 24h/28d which are accurate. They recalculate every 30 minutes. There is also a duration showing how long it took to do the queries just in case this gets slower due to bug in SQL or missing index.

chore: update dashboard with reservations stats

---

internal/kafka/notification_msg.go
internal/notifications/notifications.go

Currently, we send the generic reservation payload as the notification's context. some data is redundant (i.e. step titles, steps/step) others misleading (i.e. success flag), or might confuse - the provider's id (2) instead of the provider's string (aws).
We should send the minimal information that also will be beneficial, 
This PR replaces the reservation's payload with the `NotificationContext` struct which includes the launch_id and the provider's string, both are used in email templates.

feat(HMSPROV-2088): refacor notification's context message

---

deploy/Provisioning-1674548289785.json
deploy/dashboards/grafana-dashboard-provisioning.configmap.yaml

Duration of db stats was not summed, therefore there were incorrect (multiple) results on the dashboard.
Also, this adds a 3h reservation rate next to 24h/28d. So we can observe all the three.
I still plan on working on the alert which is not working correctly, let's use the calculated 24h for that.

chore: add 3h reservation rate and fix duration

---

internal/clients/http/ec2/ec2_client.go
internal/jobs/launch_instance_aws.go
internal/logging/sentry_replacer.go
internal/logging/sentry_replacer_test.go

Just a typo and two new Sentry replacers.

chore: fix typo and replace more identifiers

---

internal/clients/http/ec2/ec2_client.go
internal/jobs/launch_instance_aws.go

I believe this is cleaner, as the dynamic fingerprint in the error message causes trouble and we do not really care about it.
I'm happy to down level the message even as I think we already log the job error as error.

chore: remove dynamic fingerprint from error message

---

internal/dao/pgx/stat_pgx.go

I am struggling with our major SLO: reservation success rate. As you can see on our production cluster, success rate is currently below 70%. While I see about half of these failures being done by GCP which is in development, another half of the failures are AWS.
Our SLO alert currently fires "randomly" because we use prometheus counter which resets every now and than. I created a new metric that is calculated by stats process on the background (is gauge metric) and that will work, but it will cause the SLO to have a very long recovery rate because our traffic is pretty low.
Therefore I propose to change our major SLO from "success rate" to "processing rate" similarly what we do with sources availability checks. We cannot do anything if a customer fires 10 unsuccessful launches because …

fix(HMS-2143): pending state stat

---

deploy/Provisioning-1674548289785.json
deploy/dashboards/grafana-dashboard-provisioning.configmap.yaml

This improves the dashboard, I find the reservation success rate confusing as the line graph does not correspond to anything. This now has dedicated graph, stage:

chore: add process rates to the dashboard

---

deploy/Provisioning-1674548289785.json
deploy/dashboards/grafana-dashboard-provisioning.configmap.yaml

SSIA
Small typo, fixes the problem after containers are restarted - the pane shows multiple values instead of one.

chore: use sum for provisioning db duration rate

---

deploy/clowdapp.yaml

Parametrize api, worker and stats serving replicas. Statuser is always needed and there is no need to scale it up or down for now.
We want to allow scaling down of replicas for ephemeral environment.

ci: Parametrize replica counts

---

cmd/pbackend/statuser.go
internal/clients/http/ec2/iam_client.go
internal/kafka/source_result.go
internal/services/aws_iam_service.go

This adds permission logging in case of missing permissions. Caching should also be done for this. I feel like the source result should not be flagged as Unavailable or with Error in case of missing permission, as this is neither of these. Therefore, I thought adding the MissingPermission parameter might be suitable, but let me know, what you think.
For testing the missing permission in statuser, you could change iam_client hardcoded struct.

feat(HMS-1246): Use permission checks in statuser

---

cmd/pbackend/statuser.go
config/api.env.example
internal/config/config.go
internal/random/random.go

We are tracking a ticket to implement caching of source availability checks when necessary (AWS API limits). However, the numbers from both stage and production shows that we do hundreds of checks per hour, so it would be preliminary to work on this.
https://issues.redhat.com/browse/HMS-1244
However, it makes sense to prepare app configuration values just in case we hit some API limits and we will need to slow down rate of availability checks. One configuration value (delay) can be used to arbitrarily slow down pace of checks per hyperscaler. Another config value (rate) can be used for random skipping of checks in case we need to buy time in order to do proper caching implementation.
We have about 150 checks in total on stage, production is currently similar. Therefore I suggest to start …

fix(HMS-2181): statuser throttling configuration options

---

internal/clients/http/ec2/ec2_client.go
internal/clients/interface.go
internal/clients/stubs/ec2_stub.go
internal/config/helpers.go
internal/config/helpers_test.go
internal/jobs/launch_instance_aws.go

We share a team account and sometimes it is not clear who created particular instance. This should make finding owners more easier. It adds AWS instance resource tag in the form of "pr-ID" where "pr" stands for production (or st for stage, ep for ephemeral, de for development) and ID is reservation ID.

fix(HMS-2175): add AWS resource tag

---

cmd/pbackend/statuser.go
internal/clients/http/ec2/iam_client.go
internal/kafka/avail_status_msg.go
internal/kafka/kafka.go
internal/kafka/source_result.go
internal/logging/zerolog.go

So the previous fix we merged yesterday was not complete, I tested if it helped and unfortunately it did not so I kept digging. I have found a reason tho - when we receive kafka message, we extract identity, put it into a struct which is passed to worker and sending goroutines. We process everything and send it. There are problems.
We still see `Not found error from sources` and in order to find what is wrong, I need to see the whole logging transaction that can be correlated by msg_id or org_id. This is currently not possible:
First, the goroutines which are processing have context previously named `ctx` and this context is used for logging. But this is the "global" context, the logger in that context does not have the msg_id, org_id and other required fields which are needed to …

fix(HMS-2178): followup context fix for statuser

---

internal/background/availability_queue.go
internal/background/availability_queue_test.go
internal/background/initialize.go
internal/services/availability_status_service.go

We see a newly created source on stage not getting through our availability check. It is being skipped or something. There must be something wrong with the internal kafka topic. This should improve logging so we can find the particular place in logs where it should be sent.
I refactored the sending function - it takes asm instead msg so it can log source id properly.

chore: improve logging of EnqueueAvailabilityStatusRequest

---

internal/kafka/kafka.go

We have missed this, in this codeflow, the `newCtx` would end up as a 'nil' value, which we should not use anymore. This ends up with panic.

fix(HMS-2178): followup context bug fix

---

config/api.env.example
internal/background/db_stats.go
internal/config/config.go
internal/dao/dao_interfaces.go
internal/dao/pgx/stat_pgx.go
internal/dao/tests/stats_test.go

Reservations metrics are calculated ever 30 minutes and windows are 24hours and 28 days back.
This patch delays that by 10 minutes because from time to time when Azure reservation is in progress, thus in "pending" state, it is collected by Prometheus. Possibly an alert could be triggered when multiple customers would be waiting for reservation to complete. Since reservations takes from few seconds (AWS) to 9 minutes (Azure) on average, delaying the numbers for 10 minutes solves this problem completely.
The patch shorten the delay between database query from 30 to 10 minutes, since queries are about 20ms in total I think we can afford running them more often.

fix(HMS-2002): postpone db stats 10 minutes

---

internal/logging/sentry_replacer.go
internal/logging/sentry_replacer_test.go

We see bunch of Azure and GCP errors in GlitchTip, each error is unique because project id and operation start time. This makes sure all errors are grouped together.

chore: new sentry replacements

---

internal/logging/zerolog.go

Print sha commit to stdout before cloudwatch is initialized.
This will be useful during deployment to check sha commit was actually correctly deployed. You can see this in OpenShift - Pods - Pod - Logs.

chore: print version to stdout

---

deploy/testing-integration.yaml

This PR makes the following changes to the post-deploy e2e test template:
- Update resource names to not be specific to the stage environment
- Create an identifier string to pass to the test container's IQE_IBUTSU_SOURCE env value. This is used when reporting test results.
---
**Checklist**

ci(HMS-1947): Update names and add parameter in e2e test template

---

docs/configure-amazon-role.md

There was misleading information in our docs. We could merge this with some other fixes, but let's not forget this.

chore: Fix aws configuration doc

---

.rhcicd/pr_check.sh

pr_check failing because backend doesn't have the stubs https://github.com/RHEnVision/provisioning-frontend/pull/282

ci: Include image builder stub

---

internal/clients/http/ec2/ec2_client.go
internal/middleware/enforce_identity.go

Only worked when Name was provided. Name is not supported from the UI, so this is why it does not work on stage/prod. Also adding user to logging which will be useful for identification of owner of the instance.

fix(HMS-2233): fix reservation id tag for AWS

---

deploy/testing-integration.yaml

This PR updates the e2e post-deploy test template:
- The selenium container needs a higher memory limit, but can request in smaller chunks.
- The CPU chunks for the iqe container can be smaller, and its memory limit reduced
----
**Checklist**

ci(HMS-1947): Adjust memory request and limit in e2e test template

---

deploy/clowdapp.yaml

This PR enables RBAC, it will fail tests.
The following roles are required in order to perform tasks:
https://github.com/RedHatInsights/rbac-config/blob/master/configs/stage/roles/provisioning.json
These are the possible permissions:
https://github.com/RedHatInsights/rbac-config/blob/master/configs/stage/permissions/provisioning.json
Note these roles and permissions are not in production yet, I will link prod PR in a moment.

fix(HMS-1453): platform RBAC support enabled

---

internal/clients/http/ec2/iam_client.go

Wanted to make sure that the expectedStatement would not be changed, but maybe this is an overkill. Let's make it a variable.

chore: Refactor iam_client

---

internal/routes/all_routes.go

Protecting source list with RBAC is problematic for image builder which calls this endpoint. Since we do not share any data via this endpoint it is okay to have it public.

fix(HMS-1453): list sources can be public

---

internal/clients/http/sources/sources_client.go

This improves error message, currently we see this:
```
7:25AM WRN Sources did not return any Provisioning authentication for source(auth types): 7([access_key_secret_key]) account_number=0369233 client=sources hostname=provisioning-backend-statuser-798cfbfb7-df24f org_id=3340851 source_id=7 trace_id=e979b318140c108c216628100f447d60 version=dc0d
```
after we enabled SA checks. This will reveal what actually source contains so we can take it from there.

chore: improve source filtering message

---

internal/clients/http/ec2/ec2_client.go
internal/clients/http/gcp/gcp_client.go
internal/clients/instance_params.go
internal/clients/stubs/ec2_stub.go
internal/jobs/launch_instance_gcp.go

We currently do not store reservation id, the number, which is useful for figuring out owner of the instance.
While on it, I also noticed that we use fairly long "rhhhc" prefix, I propose to shorten it just to "rh".
Additionally, I noticed that AWS keys allows colons while GCP does not. Therefore I propose to use "rh-" (with dash characters) for both AWS and GCP.
The "rid" key is already used for unique identifier we generate during GCP launch, so I renamed it to "rh-uuid". It serves for identifying instances, "rh-rid" is now used for reservation numeric id. It could be used to the the same as well, but I do not want to change code too much.
Finally, keypair id was renamed to "rh-kid" to avoid too generic "id".

fix(HMS-2295): add numeric rid to GCP

---

deploy/testing-integration.yaml

This PR adds `IQE_BROWSERLOG=1` and `IQE_NETLOG=1` params / env vars to the e2e test template, so that any UI test failures will automatically capture and send browser logs to our test reporting portal.
---
**Checklist**

ci(HMS-1947): Add browser log params to e2e test template

---

internal/services/permissions.go
internal/services/permissions_test.go
internal/services/reservations_service.go

The app perform `reservation:read` check via middleware and then additional `reservation.provider:read` check in the service function. However, it is possible to read a generic reservation where the provider is set to empty string. In this case, check is performed on an incorrect resource `reservation.` (note the trailing dot) which does not match anything and the request ends up with access denied:
This refactoring fixes that, the function now takes the verb first and then arbitrary amount of resources, removes empty strings and joins them with `.` characters so this is avoided for the future.

fix(HMS-2327): fix empty resource perm check

---

internal/notifications/notifications.go

The provider's name and the launch id are not transferred correctly, which impacts the instant email template, as you can see in the following screenshot:

fix(HMS-2328): fix context in failed launch notifications

---

config/api.env.example
internal/background/cleanup.go
internal/background/initialize.go
internal/config/config.go
internal/dao/dao_interfaces.go
internal/dao/pgx/reservation_pgx.go
internal/dao/stubs/reservation_dao.go

Be careful with testing this. This will, by default, delete your reservations older than one year every one hour.
Configurable database cleanup. The default is deleting reservations older than one year every hour. I think we could maybe **improve** this by making sure users could **switch the reservation cleanup off**.
It is a bit unfortunate that the cleanenv does not offer days/years units, so we'd have to use hours even in case of a long reservation lifetime. Another thing is, that the leap year is not being taken care of. :(

feat(HMS-729): Reservations cleanup

---

CONTRIBUTING.md

In order to run `make check-commits` you need to install the changelog tool first.
**Checklist**

docs: Add missing changelog dependency to CONTRIBUTING.md

---

internal/dao/dao_errors.go
internal/dao/pgx/reservation_pgx.go
internal/payloads/error_payload.go

We currently return 500 which is not a good choice.
After the change:
```
HTTP/1.1 429 Too Many Requests
Content-Type: application/json
X-Rh-Version: 8c45 (2023-08-11T07:52:29Z)
X-Trace-Id: 5dfd8b3b28be1258d580497b648001e5
Date: Fri, 11 Aug 2023 14:46:34 GMT
Content-Length: 248
{
"msg": "too many pending reservations for this account, wait and try again",
"trace_id": "5dfd8b3b28be1258d580497b648001e5",
"error": "failed to create reservation record: rate limit exceeded: xxx",
"version": "8c45",
"build_time": "2023-08-11T07:52:29Z"
}
```

fix(HMS-2325): return 429 on rate error

---

deploy/testing-integration.yaml
deploy/testing.yaml

Update the testing templates for some new parameters, related to moving test jobs to a different cluster
Related to moving the testing to a different cluster and changing the job type used in staging:
https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/77881
**Testing**
Deployed the template to ephemeral with a local bonfire config, everything was as expected with the resulting job. 
**Checklist**
- [*] all commit messages follows the policy above
- [*] the change follows our security guidelines

test(HMS-2344): Update test templates

---

deploy/cloudwash_job.yaml

The `cron job` param was defined in `app-interface/cloudwash_saas_file ` before and it gives errors
Which says the correct location for it will `provisioning-backend` repo
Thanks, @tpapaioa for finding it

chore(HMS-1847): Updating cronjob spec

---

internal/clients/http/image_builder/image_client.go
internal/clients/http/rbac/rbac_client.go
internal/clients/http/sources/sources_client.go
internal/kafka/kafka.go
internal/migrations/migrations.go

This is the first part of the error handling fix, and also the next thing I have noticed. Sometimes, when we use defer, we do not check for errors returned from such functions. I do not think this is correct. If we have a reason we don't do that, let me know. Otherwise, I will look around the codebase to check this in more places.

fix(HMS-2258): Check errors after defer

---

internal/jobs/launch_instance_aws.go
internal/jobs/launch_instance_azure.go
internal/jobs/launch_instance_gcp.go
internal/userdata/userdata.go
internal/userdata/userdata_test.go

The whole user data (cloud init) is sent to the message field breaking the whole Kibana UI:
This fixes it.

chore: improve user data logging

---

api/openapi.gen.json
api/openapi.gen.yaml
cmd/spec/main.go
internal/payloads/pubkey_payload.go

The [OpenAPI library](https://github.com/getkin/kin-openapi) we use to generate spec, does not support descriptions for request parameters.
This enables it and adds first two descriptions.
Our Tech writers are working on helping documenting our API, so this should enable them to do so.

feat: Allow request params to have description

---

internal/jobs/launch_instance_aws.go
internal/jobs/launch_instance_azure.go
internal/jobs/launch_instance_gcp.go
internal/jobs/noop_job.go
internal/queue/stub/stub.go
pkg/worker/errors.go
pkg/worker/job.go
pkg/worker/memory.go
pkg/worker/redis.go

This is just a small change. I might wait if I find some other missing nil pointer checking. But these are our own functions with pointer parameters, so I thought I should create a PR. We can also avoid pointers in general and make the functions accept `Job` instead of `*Job`

fix: Redis nil pointers checking

---

cmd/pbackend/statuser.go
internal/kafka/source_result.go

This PR adds another field, a user friendly error msg to show on sources UI. 
* It is possible to test this only on Stage (we need the statuser listener configured locally as well).

fix(HMS-2462): Include details explaining the unavailability of a source

---

api/openapi.gen.json
api/openapi.gen.yaml
cmd/spec/parameters.go
cmd/spec/path.yaml
internal/payloads/pubkey_payload.go

* Considering only 1 endpoint (Pubkey) and 4 operation IDs under it (getPubkeyList,createPubkey,removePubkeyById,getPubkeyById)
* Removed duplicate information.
* Added detailed information of an endpoint at the top.
* Re-organised information to make the best use of space.
Feel free to suggest if there are any more modifications required. …

docs: Improve API documentation - Pubkey

---

api/openapi.gen.json
api/openapi.gen.yaml
cmd/spec/example_pubkey.go
cmd/spec/example_reservation.go
cmd/spec/example_source.go
cmd/spec/example_templates.go
cmd/spec/main.go
cmd/spec/parameters.go
cmd/spec/path.yaml
internal/clients/http/ec2/ec2_client.go
internal/clients/http/gcp/gcp_client.go
internal/clients/interface.go
internal/clients/stubs/ec2_stub.go
internal/clients/stubs/gcp_stub.go
internal/middleware/pagination_middleware.go
internal/page/page.go
internal/payloads/launch_template_payload.go
internal/payloads/pubkey_payload.go
internal/payloads/reservation_payload.go
internal/payloads/sources_payload.go
internal/routes/all_routes.go
internal/services/launch_templates_service.go
internal/services/pubkey_service.go
internal/services/reservations_service.go
internal/services/sources_service.go
scripts/rest_examples/launchtemlates-gcp-list.http
scripts/rest_examples/launchtemplates-aws-list.http
scripts/rest_examples/launchtemplates-gcp-list.http

Depends on https://github.com/RHEnVision/provisioning-backend/pull/625
This PR introduces pagination support for AWS and GCP by returning the received token when fetching the corresponding page. To validate the retrieval of AWS pages, the token needs to be escaped since it is in base64 format.
However, tests are currently missing, andI plan on adding those once will get some feedback. Additionally, tests are failing due to the initial commit missing limit and offset. I plan to stub them and proceed with adding the tests once this implementation is agreed upon.
Please let me know if you have any feedback or suggestions regarding this approach before proceeding with the test implementation.
For easy review just take a look at the changes made by the second commit, once the dependent PR will …

feat(HMS-2248): Add token support for list template

---

internal/page/page.go

Our security team runs regular penetration tests and glitchtip is cluttered with errors, I don’t think we need any logging for this it is pretty normal to expect number to convert to number and fall back to default.
I think it is worth putting limit and offset into metadata tho, because when you don’t provide it it might be useful to see the default value. But not in this PR.

chore: remove logging of bad input values

---

internal/clients/http/azure/create_vm.go
internal/clients/http/azure/create_vms.go
internal/clients/http/ec2/ec2_client.go
internal/clients/http/gcp/gcp_client.go
internal/clients/instance_params.go
internal/jobs/launch_instance_azure.go

We already have "rh-rid" for EC2 and GCP, this patch adds the same for Azure.
On top of that, this patch also adds "rh-org" with organization number. This was requested by Mike and I hope it will help to solve the problem.

fix(HMS-2545): add rh labels to all providers

---

deploy/cloudwash_job.yaml

Right now it's creating unique jobs every time.
So, to avoid that noise and expect it to override the same job for a new one, tried to remove UID and IMAGE_ID.

fix(HMS-1847): Change container name in template

---

docs/dev-environment.md
internal/clients/http/ec2/ec2_client.go
internal/clients/interface.go
internal/clients/stubs/ec2_stub.go
internal/models/reservation_model.go
internal/payloads/reservation_payload.go
internal/services/aws_reservation_service.go

Sometimes, we use pointers with no big reason. We'd dereference again and again. Sometimes it is not that needed. I split such cases into commits so that you can see which changes are related to one usage of such a variable.
I will no longer devote time to this, but these were easy changes, and there was no need to use pointers here, so I just wanted to delete these.
Before merging, I think I should merge the commits into one.

Delete simple pointers

---

internal/clients/http/gcp/gcp_client.go

There's an issue concerning GCP launch templates that involves different behaviors between the UI and API.
In the API, we  allow empty values for machine type and image ID so that users can launch instances with the properties they've defined in their templates, a feature not available in the UI.
This small fix aims to support both behaviors. On one hand, if a user provides a machine type or image ID, the instance will launch with those specified values. On the other hand, if a user selects a launch template and leaves the machine type and image ID blank, the instance will launch using the information provided in the template.
This adjustment might serves as a temporary solution for utilizing templates in GCP. I also believe it's essential to include a test for this behavior. It think it …

fix(HMS-2640): Support missing values when using launch template

---

api/openapi.gen.json
api/openapi.gen.yaml
cmd/spec/path.yaml
internal/jobs/launch_instance_gcp.go
internal/jobs/launch_instance_gcp_test.go
internal/services/gcp_reservation_service.go
internal/services/gcp_reservation_service_test.go
internal/services/reservations_service.go

Google API does not allow upper case name pattern, this PR fixes the issue and verifies the name pattern is lower cased, if not we error out.

fix(HMS-2674): Error when name pattern is invalid

---

config/api.env.example
deploy/clowdapp.yaml
docs/make.md
internal/config/config.go
internal/kafka/kafka.go

Our app expects CA cert to be present to configure TLS, in case it is blank it will not configure TLS and will attempt to connect via plain text.
The recent stage migration changed the configuration, CA cert is no longer provided. All our pods currently fail with errors "TLS is required".
This patch changes the app behavior, it is not possible to enable TLS separately via flag (enabled by default) and also skip TLS server cert validation (false at the moment, can be useful for dev setup). When CA is blank, it will pass `nil` to the Kafka client library which has documented behavior to "use host OS cert store" which is what we want.
When we merge this, it should fix the problem on stage as long as Amazon Managed Kafka CA is in the host OS cert store. If not, the workaround will be to …

fix(HMS-2703): allow to configure TLS without CA cert

---

api/openapi.gen.json
api/openapi.gen.yaml
cmd/spec/example_reservation.go
internal/jobs/launch_instance_azure.go
internal/jobs/launch_instance_azure_test.go
internal/models/reservation_model.go
internal/payloads/reservation_payload.go
internal/services/azure_reservation_service.go
internal/services/azure_reservation_service_test.go
scripts/rest_examples/http-client.env.json
scripts/rest_examples/reservation-create-azure.http

This makes the Azure resource group work as expected. The static image is expected in the same group.
Composer image is still looked up.
Fixes HMS-1772
You  won't believe it, but I've even  tested it properly and it works! xD

feat: Allow Azure resource group customization

---

internal/clients/http/sources/sources_client.go

I am trying to understand why sources randomly returns 404, there should be something in the body it looks like:
https://github.com/RedHatInsights/sources-api-go/blob/main/middleware/error_handling.go#L22C25-L22C25
This will print a warning log statement with full body as a field. @akhil-jha then let’s reproduce once again.

chore: add extra sources body logging

---

internal/clients/http/sources/sources_client.go

We see random IQE errors when sources return 500 for some reason, there is nothing interesting in (sources) logs, so let’s try to send whole body as a warning to logs to find out more:

fix: better sources non-200 logging

---

internal/dao/pgx/reservation_pgx.go

During investigation on the linked bug, I noticed this. I am not sure if this is root cause of the problems we currently see on stage, but chances are this is actually caused by the performance testing and throttle limiting.
This needs to be fixed no matter of what.

fix(HMS-2757): use transactions for reservations

---

internal/dao/pgx/pubkey_pgx.go
internal/dao/pgx/reservation_pgx.go
internal/dao/pgx/service_pgx.go
internal/jobs/launch_instance_aws.go

An error striked me this morning: "failed to save AWS pubkey name to DB: expected 1 row: unexpected affected rows" which means detail reservation could not be updated after AWS key was updated. It looks like we fetch AWS reservation detail from the database but we do not load `reservation_id` field which is okay unless we need to update such record. This field is used in the WHERE query to locate the correct record.
I am adding few more log statements to see little bit more and adding the missing field.
During this, I noticed that our reservation - detail association is set up in a way that one reservation can have multiple details for different providers. But we have never done that, our current implementation is 1:1, we might drop this in the future. But it is okay for now.

fix(HMS-2757): improve unexpected row error

---

deploy/cloudwash_job.yaml

For adding config maps into a job:
1. have already created config map yaml in app-interface
2. then referenced it to the namespace in app-interface itself.
**3. Now have added its mount point in this MR's job file**

fix(HMS-1847): Adding configmap to job

---

config/api.env.example
deploy/clowdapp.yaml
internal/config/config.go
internal/kafka/kafka.go

It looks like we use TLS on stage but not on prod and ephemeral.
This is small logging improvement that should confirm it as we do not dump configuration on prod.

chore: improve kafka startup logging

---

internal/db/connection.go
internal/identity/identity.go
internal/jobs/ctx.go
internal/jobs/launch_instance_aws.go
internal/jobs/launch_instance_azure.go
internal/jobs/launch_instance_gcp.go
internal/jobs/noop_job.go
internal/logging/ctx.go
internal/services/aws_reservation_service.go
internal/services/azure_reservation_service.go
internal/services/gcp_reservation_service.go
internal/services/noop_reservation_service.go
pkg/worker/job.go
pkg/worker/memory.go
pkg/worker/redis.go

During investigation of a problem, I noticed that worker is missing jobID from all pgx log messages therefore you will not see some records which are useful. This fixes it and unifies how context (and logger) is created across jobs. It also adds trace/edge IDs so logs can be correlated across api/worker to see the whole workflow of a reservation.
I cannot figure out why tests are failing, it is too late my brain does not work anymore. Will take a look tomorrow.

chore: correlation for worker logger

---

internal/dao/pgx/account_pgx.go
internal/middleware/account.go

So I came up with this nice trick on how to quickly create accounts without explicit transactions. Works great, except it does not :-) When there are actually two requests with the same account at the same time, the query is executed in an implicit transactions which cannot be turned off and I totally forgot about it.
What happens is that one request will fail with `pgx error: scanning one: no rows in result set` (https://glitchtip.devshift.net/insights/issues/973561) because although the conflict will trigger, the default isolation level in postgres will not allow to see the inserted record.
The solution is to execute the same query one more time, this only happens rarely, I saw 20 events in production in one week. But it is worth fixing this.
This is hard to test or reproduce, so review …

chore: requery account for transaction isolation

---

deploy/clowdapp.yaml

How to test this:
`curl --http2 .... stage_url`
Stage environment is accessible via the proxy and I just verified that HTTP2 works fine through curl, let’s merge this and see if it is disabled.

fix: workaround for CVE-2023-44487

---

internal/middleware/logger.go

SSIA
Our 3scale API uses HTTP/2 for client communication but internally I believe it relies on HTTP 1.1. This should confirm this.

chore: log HTTP protocol in request start

---

internal/telemetry/zerolog_exporter.go

We do not include slices in our telemetry2zerolog implementation, the otelpgx library does use string slice for params. This was the reason why it was missing. This fixes it.

chore: add otel pgx parameters to log

---

internal/db/connection.go
internal/identity/account.go
internal/jobs/ctx.go
internal/logging/ctx.go
internal/telemetry/zerolog_exporter.go
pkg/worker/job.go

Add few more important correlation params into otel logger, also store job id and type in context for later use. Finally, rename one context function to better reflect what it returns.

chore: add more otel params

---

internal/background/db_stats.go

Something does not work right, the numbers in the logs and prometheus/graphana do not match. This should show more insights.

chore: log stats structure alongside totals

---

deploy/clowdapp.yaml

I noticed we do not make statistics of gcp provider. :eyes: I understand that the floorplan is old, but I hope we can do this now.
Please, do not merge yet, I am thinking if I would add something else. But could you please check if this would not break the process?
note: We only track whether or not the users use any template, but we do not track what is in the template. We could add the template to the floorplan in the future, but we'd most likely have to export the template for each reservation detail. I remember @lzap wanted to track this, so I am just saying it is possible. But it seems it would complicate the data, so I would postpone it a bit.

chore: Add GCP provider to floorist

---

pkg/worker/job.go
pkg/worker/memory.go
pkg/worker/redis.go

:tipping_hand_person:  depends on #711 and thus contains those changes as well
Cleans up job logs.
Removes job_args from most of the job logs except Enqueue and Dequeue.
Removes double logging of job id and type.
I was touching this code quite heavily in #711 so I wanted to follow-up with what I feel might improve the logging a bit.
:warning: These are my opinions and maybe some of the logs were there on purpose, happy to discuss it! :)

chore: Sanitize job logging 

---

docs/opentelemetry.md
internal/cache/redis.go
internal/clients/http/azure/azure_client.go
internal/clients/http/azure/azure_common.go
internal/clients/http/azure/create_vm.go
internal/clients/http/azure/create_vms.go
internal/clients/http/ec2/ec2_client.go
internal/clients/http/gcp/gcp_client.go
internal/clients/http/image_builder/image_client.go
internal/clients/http/rbac/rbac_client.go
internal/clients/http/sources/sources_client.go
internal/jobs/common.go
internal/jobs/launch_instance_aws.go
internal/jobs/launch_instance_azure.go
internal/jobs/launch_instance_gcp.go
internal/kafka/kafka.go
internal/middleware/telemetry.go
internal/telemetry/otel.go
pkg/worker/job.go

Extract span start into a separate function.
This also obsoletes the Tracer naming per package, which is actually correct
According to Tracer docs https://pkg.go.dev/go.opentelemetry.io/otel/trace@v1.16.0#TracerProvider
the passed name should be a name of a tracing library, not the package being intrumented.
Follows #711 with cleanup of `TraceName` we got it wrong according to [docs](https://pkg.go.dev/go.opentelemetry.io/otel/trace@v1.16.0#TracerProvider).
More info is also in these nice docs: https://uptrace.dev/opentelemetry/go-tracing.html#tracer

chore: start spans only when telemetry is enabled

---

deploy/clowdapp.yaml

I will probably add the whole template later, but for now let's just see if the "is not null" does not misbehave, since we are using an empty string and not a null value.

chore: Include reservation template ID in Floorplan

---

deploy/clowdapp.yaml

I do not wish to make a nightmare commit history. But I guess we are not able to test this until we find out that we broke the process. And it seems to be broken right now, we are not getting the latest data, unfortunately. I think I have found the reason, after incorporating the gcp, we still could have fetched the data, so I hope that it is only this.
I think that since I have recreated the field into a string field, it was wrong to leave the boolean for Azure.

Fix: SQL Union on different datatypes

---

cmd/spec/example_reservation.go
internal/dao/dao_errors.go
internal/dao/pgx/reservation_pgx.go
internal/dao/tests/reservation_test.go
internal/jobs/launch_instance_aws_test.go
internal/jobs/launch_instance_azure_test.go
internal/jobs/launch_instance_gcp_test.go
internal/migrations/sql/021_remove_delete_cascade.sql
internal/migrations/sql/022_pubkey_nullable.sql
internal/models/reservation_model.go
internal/payloads/reservation_payload.go
internal/services/aws_reservation_service.go
internal/services/azure_reservation_service.go
internal/services/gcp_reservation_service.go
internal/services/reservations_service.go
internal/services/reservations_service_test.go

So I think this should do. I forgot to set pubkey_id nullable and could not find rollback, so I have two migrations.
Tested scenario: create key, create a reservation with the key, delete the key, GetReservationById.
In this sequence of steps, this all works as expected; we do not have any pubkey id, and GetReservationById returns a response with no pubkey_id. All occurrences of PubkeyId for both responses and pubkey models should be covered by checking for nil pointers, and we should keep in mind, that we do allow empty pointers here.

fix(HMS-2757): Do not cascade on pubkey delete

---

deploy/cloudwash_job.yaml

The env_vars which is being used by config map is defined under cronjob yaml.
which needs to be defined under the container block instead of the volum_mounts block.

fix(HMS-1847): Updating env_var variables location

---

deploy/clowdapp.yaml

Do not merge yet.
This is a PR to remind us we need to revert this workaround in the future.

chore: revert workaround for CVE-2023-44487

---

deploy/Provisioning-1674548289785.json
deploy/dashboards/grafana-dashboard-provisioning.configmap.yaml

The last panel says 24h, but it should be 28d IMO :)

chore: Fix typo in a chart label

---

internal/dao/pgx/account_pgx.go

The scanning function returns no rows error so the previous patch was not working. Indeed, there are no "requery" log statements on stage.
It is really hard to write a test for this, I would need to create many goroutines, we have tests for successful cases.

chore: fix account requery

---

docs/configure-gcp.md

Thanks a bunch for providing the commands @pablomh !

docs: default GCP networking documentation

---

api/openapi.gen.json
api/openapi.gen.yaml
cmd/spec/path.yaml

Add descriptions to tags, as some libraries read the tags from tag list only.
Also moves the availability endpoint to Source tag, as it felt kinda lonely in the tag by itself and Source felt like a good home for it :)
For example RH api-catalog:

docs: Add descriptions to all tags

---

api/openapi.gen.json
api/openapi.gen.yaml
internal/jobs/launch_instance_azure.go
internal/payloads/reservation_payload.go
internal/services/azure_reservation_service.go
internal/services/azure_reservation_service_test.go

This adds ability to pass the optional name of the instance. If the name is not passed, we use redhat-vm as default name.
This also removes location from the response, if location was not explicitly passed by user.
Refs HMS-2004 , HMS-2923

feat: Support naming Azure instances

---

.github/workflows/gotest.yml
deploy/clowdapp.yaml

Production database is already on v15, Integration tests were pulling latest v16 and ephemeral used v13. This changes all postgres versions to v15.

ci: Use the same postgres version in all environments

---

.github/workflows/gotest.yml

I'm opening up just for a discussion, happy to close this one.
This is just a feeling based combination to safe bit of resources on setting up containers.
OTOH the separation makes the failure bit more readable without opening the logs :)

ci: Combine commit checks into one check

---

.pre-commit-config.yaml
internal/kafka/kafka.go

Code-wise everything is okay and we already use multiple kafka brokers. It is just we haven’t deployed into stage for quite a bit and I do not see any of the messages, this small fix will trigger deployment so I can investigate the string on stage.

fix(HMS-3000): update log statement for kafka

---

cmd/pbackend/statuser.go
internal/clients/http/sources/sources_client.go
internal/payloads/validation/id.go
internal/payloads/validation/id_test.go
internal/services/aws_iam_service.go
internal/services/launch_templates_service.go
internal/services/pubkey_service.go
internal/services/sources_service.go
internal/services/sources_status_service.go

Hopefully this should be okay.
I am not entirely sure, if ParseUint would prevent out of range error. Maybe sources use ParseInt, and I just added a bigger range for them.
Also, I think, that they validate with different regex: https://github.com/RedHatInsights/sources-api-go/blob/4a3475e59b8f515dbda70c423826b2a3e4d07cb6/middleware/id_validation.go#L14, and I do not think that this is correct tbh, so I did this my way.
This is still WIP, but I wanted you to be able to comment on this in advance.

fix(HMS-2933): Improve some HTTP error codes

---

internal/clients/http/sources/sources_client.go
scripts/rest_examples/sources-list.http

Extracts funcionality that was duplicated between ListSources and ListSourcesByProvider. Keeps the unique bits and thus both functions.
This way it will be easy to merge the functions once sources support the filtering through OpenAPI client.

refactor: extract common funcionality of listing sources

---

deploy/cloudwash_job.yaml

Have added a new vault path for only secrets.
https://vault.devshift.net/ui/vault/secrets/insights/show/secrets/qe/global/hms/azure
and removed the location and resource group field of auth from the previous path.
now pod spec will fetch the location and resource group value from the configmap file instead of overriding it from the secrets file.

fix(HMS-1847): Removing location and resource group

---

internal/clients/http/ec2/ec2_client.go
internal/clients/stubs/ec2_stub.go
internal/clients/stubs/sources_stub.go
internal/payloads/error_payload.go
internal/services/sources_service_test.go

AssumeRole is supposed to assume the role that client is giving us. This fixes the error code when this operation fails.
It could have also been 401 as the role might be considered an input. Given this is a permissions operation, I went with 403.
Let me know if you think 401 (or any other code) would be more fitting.
I've went bit overboard to mimic the error that AWS returns in our stub.
But now it should test the real thing pretty closely.

fix(HMS-3185): fail with 403 on failed assume role

---

.rhcicd/pr_check.sh

Bonfire repository for pr_checks is now legacy. 
cicd-tools repo has the latest changes.

ci: Change CICD_URL for pr_check

---

internal/logging/sentry.go
internal/logging/sentry_replacer.go
internal/logging/sentry_replacer_test.go
internal/logging/zerolog.go

With implementing the replace functionality as Sentry hook,
we can implement it bit more efficiently for only messages that are sent to sentry.
It also allows us to use the sentry writer as LevelWriter and leverage WriteLevel function.
WriteLevel is bit more streamlined as it allows to skip filtering when not needed.

fix(HMS-3369): Implement replacing as beforeSend hook

---

internal/background/availability_queue.go

We are seeing major slow down in queing up the availability status checks after certain amount of checks are queued up.
This doubles the channel size in hope the requests can be queued up in channel in the meantime when the previous batch is being send to kafka. This is just a guess for the cause, thus this also adds telemetry, so we have bit more info.
Refs HMS-3415

fix: Double the availability request channel size

---

internal/background/availability_queue.go
internal/background/initialize.go
internal/metrics/metrics.go
internal/metrics/registration.go

I believe these delays are caused by slow Kafka batch send. This patch makes the sending async, this requires full copy of the buffer to prevent random misbehaviour and a wait group to ensure all messages are flushed on restart. Additionally, I have added new duration metric to actually see how slow this is. Also I slightly increase the buffer size and incoming queue, although I think it will be only the background processing what will help to solve the situation as the problem is really in pace of incoming request being much faster than sending.

feat: async avl check kafka send

---

deploy/cloudwash_job.yaml

Cloudwash pod args have a small fix.
The cmd should be 
`aws -d --vms` instead of `aws -d --vm`

Fix aws args

---

internal/background/initialize.go

It looks like on stage the largest cumulated checks is around 175, this gets sent in 7 batches. This should be similar on prod as well as there are also two goroutines sending the requests from sources. Increasing to 64 will half number of goroutines spawned.

chore: further increase AVL batch size

---

deploy/testing-integration.yaml

Disabling parallel test execution considering current failure for hms-integration testing workflow.

ci: Parallel test execution disabled

---

deploy/testing-integration.yaml

Imagebuilder navigation in beta has lots of new elements due to blueprints. This breaks the existsing hms-integration test. 
The use_beta flag will be turned true when the navigation exists in the qe repo.

ci: Disable beta integration testing for backend repo

---

internal/config/config.go

fix(HMS-3760): Remove Bearer from Unleash auth header

---

deploy/testing-integration.yaml

Continuing from https://github.com/RHEnVision/provisioning-backend/pull/787 (I messed up my remote :) )

ci(IQE-2748): Update sel testing image backend

---

deploy/testing-integration.yaml

Same as https://github.com/RHEnVision/provisioning-frontend/pull/404 .
"New sel image is failing the test pipeline because it does not have a controlled shutdown command, making the pod stuck and resulting into timeout."

ci(IQE-2748): Revert Update sel testing image backend

---

.rhcicd/pr_check.sh

This will deploy the apps using whatever is in stage which is where PRs are deployed after being merged.
**Checklist**

pr_check: use insights-stage as ref-env

---

deploy/clowdapp.yaml

See ADR-046 for more details.
This app is very small, minimal traffic, these are the smallest values I have seen in the examples so let’s go with this.

fixes(HMS-4439): resource limits (ADR-046)
