RHEnVision/provisioning-backend

- Makefile
- cmd/pbapi/main.go
- cmd/pbmigrate/main.go
- go.sum
- internal/db/connection.go
- internal/db/migrations.go
Migration was previously hardcoded to localhost, it now respects configuration via ENV variables. I also improved logging and it shows migration history after each migration too.
> Migration respect configuration

- internal/db/seeds/drop_all.sql
This script is only used for testing, I use it to cleanup the database from scratch.
> Use drop schema instead of drop table

- go.mod
- go.sum
- internal/config/config.go
- internal/models/pubkey_resource_test.go
Needs to add stubbing for Dao, which is bit clunky.
> Add unit test for model

- internal/db/connection.go
Logging from the pgx driver was not working properly because the connection was not made from the registered driver.
> Register pgx logging properly

- cmd/pbapi/main.go
- internal/config/config.go
- internal/routes/all_routes.go
Please advice on the config option names and nesting :cry: 
**Checklist**
> Configurable mounting point

- .github/workflows/gotest.yml
- Makefile
- cmd/pbapi/main.go
- cmd/pbmigrate/main.go
- internal/config/0-config.go
- internal/config/5-devel_config.go
- internal/config/5-test_config.go
> Environment aware config initialization

- .github/workflows/gotest.yml
- Makefile
**Checklist**
We are pinning to a specific version because of this https://github.com/golangci/golangci-lint/issues/2851
> Change golangci version in makefile

- internal/config/main_config.go
Can we merge this BEFORE I present jobsqueue tomorrow :-)
> Filter out AWS secrets from logs

- deploy/bonfire.example.yaml
the bonfire config yaml file  has renamed due to depreciation
> Fix bonfire config path

- go.mod
- go.sum
- internal/ctxval/ctx_getters.go
- internal/routes/all_routes.go
- internal/services/pubkey_service_test.go
- internal/test/identity/dummy_identity.go
- internal/testutils/dummy_identity.go
Add support for passing down the identity into the application.
Add support for stubbing the identity with constant identity for 
testing.
**Checklist**
> Add support for X-RH identity

- scripts/rest_examples/http-client.env.json
- scripts/rest_examples/pubkey-create-failure.http
- scripts/rest_examples/pubkeys-create-success.http
- scripts/rest_examples/pubkeys-delete-all.http
- scripts/rest_examples/pubkeys-delete.http
- scripts/rest_examples/pubkeys-get.http
- scripts/rest_examples/pubkeys-list.http
- scripts/rest_examples/pubkeys-upload-aws.http
SSIA
This is only used for testing, GoLand and VSCode do support these.
> Add identities to .http test clients

- .gitignore
- Makefile
@lzap this is not needed now, right?
> Replace gomigrate by tern in tools

- internal/db/seeds/dev_small.sql
- internal/payloads/error_payload.go
- internal/payloads/sources_payload.go
- internal/routes/all_routes.go
- internal/services/headers.go
- internal/services/sources_service.go
Depends on https://github.com/RHEnVision/provisioning-backend/pull/31
> List sources and Get source using Sources Client

- internal/clients/sources/sources_impl.go
- internal/clients/sources/sources_interface.go
- internal/payloads/sources_payload.go
- internal/services/sources_service.go
> Add sources integration an interface and implementation

- internal/clients/sources/stubs/sources_stub.go
- internal/services/sources_service_test.go
@lzap, @ezr-ondrej  Not sure if those tests are sufficient but please share your thoughts, this PR is based on Ondrej's previous testing.
> Add tests for ListSources and GetSource

- .github/workflows/gotest.yml
by using github actions.
used #28
> Validate and compare  OpenAPI Spec

- scripts/sources.clean.sh
- scripts/sources.conf
- scripts/sources.seed.sh
- scripts/sources.setup.sh
- scripts/sources.start.sh
Solved https://github.com/RHEnVision/provisioning-backend/pull/54#pullrequestreview-1012697709
> Make scripts to work from any directory

- configs/defaults.yaml
- internal/clients/sources/sources_impl.go
- internal/clients/sources/sources_interface.go
- internal/clients/sources/stubs/sources_stub.go
- internal/config/5_real_config.go
- internal/config/5_test_config.go
- internal/config/main_config.go
- internal/services/sources_service.go
> Change List Sources to consider application type

- api/openapi.gen.json
- api/openapi.gen.yaml
- cmd/spec/main.go
- cmd/spec/path.yaml
This PR adds sources type and paths to the spec file
blocked by #63
> Add sources to spec file

- deploy/clowdapp.yaml
Adding sources as dependency so it gets deployed when provisioning-backend gets deployed.
> Add sources under dependencies in clowdapp.yaml

- scripts/identity_header.sh
> Make identity script MacOS compatible

- api/openapi.gen.json
- api/openapi.gen.yaml
- cmd/spec/main.go
- cmd/spec/path.yaml
- internal/payloads/instance_types_payload.go
> Add list instance types to spec

- Makefile
- internal/config/5_real_config.go
Endpoint is a struct, we need to build the URL from it.
> Build the sources URL from Endpoint

- scripts/rest_examples/http-client.env.json
- scripts/rest_examples/instancetypes-list.http
> Fix prefix in http client environment

- docs/configure-amazon-role.md
SSIA
Please test this step by step before merging, we need to be sure this works out of box.
> Add documentation for AWS IAM Role configuration

- internal/ctxval/ctx_getters.go
- internal/ctxval/ctx_keys.go
- internal/dao/dao_interfaces.go
- internal/dao/sqlx/account_dao.go
- internal/middleware/account.go
- internal/routes/all_routes.go
Adds Account to the context if found by identity information present in the header.
Test is separate in #92 as it needs #91 first and I didn't want to do #91 in this PR
> HMSPROV-137: Get account from identity

- internal/middleware/account_test.go
- internal/testing/identity/dummy_identity.go
Tests for #90, but need to have #91 in first, so creating separate draft PR.
> Test account middleware

- go.mod
- internal/dao/stubs/account_dao.go
- internal/pointer/pointer.go
- internal/services/sources_service_test.go
SSIA
We already have that dependency because AWS SDK use it anyway.
> Use ptr package from AWS smithy project

- internal/dao/sqlx/pubkey_dao.go
I've run into this while testing.
> Fixes UpdatePubkey

- internal/dao/stubs/context_getters.go
- internal/dao/stubs/model_factories.go
- internal/dao/stubs/pubkey_dao.go
- internal/dao/stubs/stub_errors.go
- internal/services/pubkey_service_test.go
Implements all DAO functions properly.
Implements pubkey generation.
Hides out the DAO stub structure, so it can't be manipulated from outside.
> Improve pubkey DAO stub

- Makefile
- cmd/dao_tests/pubkey_test.go
- internal/db/seeds/dao_test.sql
> Db tests simple

- internal/clients/sources/sources_client.go
- internal/clients/sources/sources_client_test.go
- internal/clients/sources/sources_errors.go
- internal/clients/sources/sources_interface.go
- internal/clients/sources/stubs/sources_stub.go
- internal/headers/headers.go
- internal/routes/all_routes.go
- internal/services/instance_types_service.go
- internal/services/sources_service.go
- internal/services/sources_service_test.go
Switch sources client to a new one.
> Add sources wrapper client

- internal/dao/dao_errors.go
- internal/dao/sqlx/account_dao.go
- internal/dao/sqlx/pubkey_dao.go
- internal/dao/stubs/context_getters.go
- internal/dao/stubs/pubkey_dao.go
Fixes HMSPROV-157
TODO: do the same for stubbed dao, once #102 is in.
> HMSPROV-157: Guard Pubkey DAO by tenant

- internal/dao/sqlx/reservation_dao.go
- internal/db/migrations/005_reservations.sql
- internal/models/reservation_model.go
- internal/payloads/reservation_payload.go
- internal/services/aws_reservation_service.go
This is a DRAFT 😄 
seems like the reservation was created correctly
> HMSPROV-154: Add data for aws launch instance

- Makefile
- cmd/dao_tests/pubkey_test.go
- internal/db/seeds/dao_test.sql
I have few thoughts on this:
1) Is it safe to check with values from seed files? Are we not going to change the values in the process of development?
2) Should we come up with more detailed errors for failed tests?
> Integration Test for Pubkeys DAO

- pr_check.sh
should have removed this with the fix of the clowdapp template
> Update pr_check component

- api/openapi.gen.json
- api/openapi.gen.yaml
- internal/clients/client_models.go
- internal/clients/clients_interfaces.go
- internal/clients/sources/sources_client.go
- internal/clients/sources/sources_impl.go
- internal/clients/sources/sources_interface.go
- internal/clients/sources/stubs/sources_stub.go
- internal/jobs/pubkey_upload_aws_job.go
- internal/payloads/sources_payload.go
- internal/services/instance_types_service.go
- internal/services/sources_service.go
- internal/services/sources_service_test.go
Define our source model and use that instead of generated one.
> Define source model ourselves

- .github/CODEOWNERS
@RHEnVision/qe does that make sense to you?
> OpenAPI spec owned by QE

- cmd/dao_tests/reservation_test.go
- internal/db/seeds/dao_test.sql
> HMSPROV-79 Reservation dao test

- internal/clients/ec2/ec2_client.go
- internal/dao/dao_interfaces.go
- internal/dao/sqlx/reservation_dao.go
- internal/db/migrations/002_utility_functions.sql
- internal/db/migrations/005_reservations.sql
- internal/jobs/launch_instance_aws.go
- internal/jobs/pubkey_upload_aws_job.go
- internal/jobs/queue.go
- internal/models/reservation_model.go
- internal/services/aws_reservation_service.go
- scripts/rest_examples/reservation-create-aws.http
If you have a better naming suggestions I am happy to hear 😄
> HMSPROV-153: Add launch instance aws job

- cmd/dao_tests/reservation_test.go
- internal/models/reservation_model.go
> HMSPROV-181: Add dao test for instance_reservation

- internal/clients/clients_interfaces.go
- internal/clients/image_builder/image_client.go
- internal/clients/image_builder/image_errors.go
- internal/clients/image_builder/stubs/image_builder_stub.go
> add image builder service for AMI

- cmd/dao_tests/pubkey_test.go
- cmd/dao_tests/reservation_test.go
- internal/db/migrations/005_reservations.sql
- internal/db/seeds/dao_test.sql
- internal/jobs/launch_instance_aws.go
- internal/jobs/pubkey_upload_aws_job.go
- internal/models/reservation_model.go
- internal/payloads/reservation_payload.go
- internal/services/aws_reservation_service.go
- scripts/rest_examples/reservation-create-aws.http
Also move pubkey upload to a job.
I am currently having issues with my Role/STS setup (getting permission denied). Please test the patch carefully :)
> Remove pubkey from reservation endpoint

- internal/payloads/error_payload.go
- internal/services/aws_reservation_service.go
- internal/services/instance_types_service.go
- internal/services/sources_service.go
A suggestion to make the error more general so we could use it for image builder client and others
> Change SourcesClientError to ClientError

- .github/workflows/gotest.yml
> Update GHA actions to latest versions

- internal/logging/zerolog.go
- internal/logging/zerolog_test.go
Copy pasted from stack overflow without unit tests!
Oh my me.
> Fix incorrect string truncation in logger

- internal/clients/image_builder/image_client.go
During testing the IB client with #150, it ended with panic due to a failure in a casting.
Verified with ImageBuilder stage
> Fix IB client

- internal/dao/sqlx/reservation_dao.go
- internal/db/migrations/005_reservations.sql
- internal/models/reservation_model.go
- internal/services/aws_reservation_service.go
- scripts/rest_examples/ib_list.http
- scripts/rest_examples/reservation-create-aws.http
> Use GetAWSAmi of image builder client

- internal/cache/lru.go
The linter keeps adding this change, Can we change it?
> Add golang lint suggestion

- internal/dao/sqlx/pubkey_resource_dao.go
- internal/db/migrations/004_pubkeys.sql
- internal/jobs/pubkey_upload_aws_job.go
- internal/models/pubkey_resource.go
- internal/models/pubkey_resource_test.go
- internal/services/aws_reservation_service.go
Please, let me know if we need to change Source ID in updatePubkeyResource. :) I was not sure about that one. Both integration and unit test are passing.
> Add Source ID

- api/openapi.gen.json
- api/openapi.gen.yaml
- cmd/spec/path.yaml
> HMSPROV-199: OpenAPI: Pubkey get and list payload fix

- cmd/dao_tests/account_test.go
> Db tests account

- api/openapi.gen.json
- api/openapi.gen.yaml
- cmd/spec/path.yaml
Please let me know if I have to add anything anywhere else too!
> Add requestbody to POST /pubkeys

- api/openapi.gen.json
- api/openapi.gen.yaml
- cmd/spec/main.go
- cmd/spec/path.yaml
- internal/payloads/reservation_payload.go
- internal/services/aws_reservation_service.go
@lzap Can you take a look at the descriptions I wrote? I think they lack information :)
> Add reservation to OpenApi

- .gitignore
- Makefile
> Remove pbworker binary from the repository

- configs/ib_api.yaml
- internal/clients/image_builder/client.gen.go
- internal/clients/sources/sources_client_test.go
SSIA
There was an unused client test, perhaps generated by the tool.
> Regenerate clients and delete unused test

- internal/services/noop_reservation_service.go
> Use Account from headers in NoopService

- internal/clients/sources/sources_client.go
The request returns 401 from sources api, adding identity header fix it
> add identity header to ListApplicationTypes

- deploy/clowdapp.yaml
- internal/config/0_common_config.go
We have an account in the secrets now, lets set it in the ENV.
Fixes HMSPROV-203
> Set AWS credentials from kub secret

- internal/clients/ec2/ec2_client.go
- internal/services/instance_types_service.go
After reading some documentation it seems that we have two ways in order to present a complete instance types list. 
1. Using the token given in DescribeInstanceTypesOutput: https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/ec2#DescribeInstanceTypesOutput and fetch the instance types until the token is nil.
2. Use NewDescribeInstanceTypesPaginator as implemented in this patch. 
It seems like both ways are based on the same idea but we can improve the performance of the second option of DescribeInstanceTypesPaginator using go routines as used here: https://github.com/firekillice/filebeat-kafka-mongo/blob/703d589a09cfdbfd7f84c1d990b50b6b7f62ac29/x-pack/libbeat/autodiscover/providers/aws/ec2/fetch.go#L83
**( It took about 5 seconds to get all the data after filtering, there are 557 …
> Use paginator to list instance types

- internal/services/instance_types_service.go
- scripts/rest_examples/http-client.env.json
- scripts/rest_examples/instancetypes-list.http
> Update types .http file and update log line

- api/openapi.gen.json
- api/openapi.gen.yaml
- cmd/spec/path.yaml
- internal/clients/ec2/ec2_client.go
- internal/clients/ec2/ec2_errors.go
- internal/services/instance_types_service.go
- scripts/rest_examples/http-client.env.json
- scripts/rest_examples/instancetypes-list.http
NEXT: to add the change in all the jobs as well
> Add region to instance type endpoint

- api/openapi.gen.json
- api/openapi.gen.yaml
- cmd/spec/path.yaml
> List responses need array schemas

- cmd/dao_tests/account_test.go
- cmd/dao_tests/main_test.go
- cmd/dao_tests/pubkey_resource_test.go
- cmd/dao_tests/pubkey_test.go
- cmd/dao_tests/reservation_test.go
- internal/models/pubkey_resource.go
I think we might have a copy paste mistake in pubkey_resource.go, but I did not want to make a PR just for that.
> HMSPROV-79 Resource tests

- internal/dao/tests/account_test.go
- internal/dao/tests/pubkey_test.go
- internal/dao/tests/reservation_test.go
Changes based on suggestions from Lukas.
> Refactor integration tests

- deploy/clowdapp.yaml
> Change iqe plugin name in clowder

- internal/clients/clients_errors.go
- internal/clients/http/ec2/ec2_client.go
- internal/clients/http/ec2/ec2_errors.go
- internal/clients/http/error_handling.go
- internal/clients/http/image_builder/image_client.go
- internal/clients/http/image_builder/image_errors.go
- internal/clients/http/sources/sources_client.go
- internal/clients/http/sources/sources_errors.go
- internal/jobs/pubkey_upload_aws_job.go
- internal/parsing/parsing.go
- internal/services/aws_reservation_service.go
- internal/services/instance_types_service.go
SSIA
FYI this is broken into separate commits for easier review.
> Improve error handling of sources client

- internal/services/instance_types_service_test.go
Azure instance types has been merged without any test.
> Add test for Azure instance types service

- docs/configure-amazon-role.md
- docs/dev-environment.md
This tries to improve our AWS guide to explain all the quirks. It tries to explain the production workflow, while also give away easy steps for development.
> Explain our workflow in AWS further

- internal/config/0_common_config.go
- internal/dao/tests/main_test.go
> Fix Viper Default Values

- deploy/clowdapp.yaml
Reverts RHEnVision/provisioning-backend#226
> Revert "Rename database to match stage"

- deploy/clowdapp.yaml
Stage environment forces this key format, I've fixed this in ephemeral secrets and now this is the only thing left to finish the switch :)
> Use same secret keys in all environments

- internal/dao/sqlx/pubkey_resource_dao.go
- internal/dao/tests/pubkey_resource_test.go
- internal/db/migrations/009_add_region.sql
- internal/models/pubkey_resource.go
We need a region for a pubkey. I felt this should belong to PubkeyResource. Correct me if I am wrong. I was not sure if the region should be required, but I felt like that should not be a problem. The value is prefilled for now.
> Add Region To PubkeyResource Model

- internal/payloads/reservation_payload.go
Fixes HMSPROV-253
@akhil-jha is that what you were talking about? :)
> Add pubkey id to AWS response

- internal/clients/http/ec2/ec2_client.go
- internal/clients/http/ec2/ec2_logging.go
- internal/jobs/pubkey_upload_aws_job.go
> Set pubkey aws resource region on create

- internal/dao/dao_interfaces.go
- internal/dao/pgx/pubkey_pgx.go
- internal/dao/stubs/pubkey_dao.go
- internal/dao/tests/pubkey_resource_test.go
- internal/jobs/pubkey_upload_aws_job.go
It wasn't clear from the function name if I am listing pubkeys or resources or what exactly.
> Rename Pubkey Resource DAO functions

- internal/clients/http/ec2/ec2_client.go
Only to the most important functions.
> Add otel to EC2 client

- internal/services/instance_types_service.go
> Remove unnecessary error check

- .chglog/CHANGELOG.tpl.md
- .chglog/config.yml
- .github/workflows/gotest.yml
- CHANGELOG.md
- mk/code.mk
- mk/tools.mk
- scripts/check_commits.sh
This is a proposal to enforce more user-friendly commit messages which allows nicer CHANGELOG generation and history tracking of features and bugs. It introduces https://github.com/git-chglog/git-chglog tool, a CHANGELOG file generator. It also adds GHA that enforces few simple rules on commits:
* Must start with: chore demo docs feat fix refactor revert style test
* Optionally can contain subject of commit in the form of `type(subject): xxx`
* Maximum length of 70 characters (for easier text terminal use)
Additional recommendations (not enforced):
* Use lower-case everywhere, except function names or acronyms etc.
* Commit messages should not be sentences, avoid verbs, skip articles, be short.
* Don't hesitate to continue with explanation in the commit body.
Example commits:
* `feat: new …
> Add CHANGELOG and GHA commit action

- api/openapi.gen.json
- api/openapi.gen.yaml
- cmd/spec/path.yaml
- internal/db/migrations/011_delete_cascade.sql
- internal/services/pubkey_service.go
This is not tested at all and is just a draft. There are no tests for DELETE. How should we test this?
> HMSPROV-127 Delete Pubkey Resource

- internal/payloads/error_payload.go
- internal/services/aws_reservation_service.go
- internal/services/builtin_types_service.go
- internal/services/gcp_reservation_service.go
- internal/services/instance_types_service.go
- internal/services/instance_types_service_test.go
- internal/services/noop_reservation_service.go
- internal/services/pubkey_service.go
- internal/services/reservations_service.go
- internal/services/sources_service.go
- internal/services/sources_status_service.go
- internal/services/status_service.go
This PR should contain some of the 'less questionable' error refactoring. More or less, this is just coming up with user-facing error messages.
This also removes the Dao Initialization error since we no more return errors for the initialization.
> Error improvements 2

- internal/jobs/queue/dejq/dejq_queue.go
This fixes the problem we saw, we have modified a configuration via app-interface which broke all deployments which were not rebased on the Redis PR.
This should at least give a nicer error message to these.
All: Rebase all PRs on top of `main` to get Redis support which has been configured in app-interface already.
> fix(queue): recognize unknown worker config values

- cmd/pbapi/main.go
- deploy/clowdapp.yaml
- go.mod
- go.sum
- internal/clients/http/interface_doer.go
- internal/config/config.go
- internal/config/flags.go
- internal/config/flags_listener.go
- internal/config/helpers.go
- internal/ctxval/context_values.go
- internal/middleware/account.go
- internal/routes/all_routes.go
- internal/services/error_renderer.go
- internal/services/feature_flags_service.go
- internal/services/reservations_service.go
- internal/services/sources_status_service.go
- internal/services/status_service.go
- internal/version/version.go
- scripts/rest_examples/feature-launch.http
https://issues.redhat.com/browse/HMSPROV-314
Implements feature flag endpoint that our/ib UI will use to show/hide the launch button. The backend service we use is named Unleash
* https://www.getunleash.io/
* https://github.com/Unleash/unleash
* https://github.com/Unleash/unleash-client-go
Therefore all the configuration variables are also named `UNLEASH_` and it is possible to configure the service locally and enable it for debugging purposes. When Unleash is disabled through config, all queries for feature flags return true. When running in Clowder, Unleash gets enabled by default and configured from Clowder.
> feat(flags): feature flags endpoint

- .gitignore
JetBrains Fleet is their new complementary VSCode IDE that is currently in preview. I am trying it and it looks it works great, even over SSH which is what I mostly work (I am on Mac SSHing to my Fedora servers). Very nice and clean interface, easy to remember hotkeys and pretty fast.
This adds required gitignore.
I highly suggest to check it out, if anybody is interested here is my Run Configurations (`.fleet/run.json`). You need to figure out this one from the docs: https://www.jetbrains.com/help/fleet/run-configs.html
```json
{
"configurations": [
{
"name": "migrate",
"workingDir": "$USER_HOME$/work/provisioning-backend",
"type": "go",
"goExecPath": "$USER_HOME$/sdk/go1.18/bin/go",
"buildParams": [
"github.com/RHEnVision/provisioning-backend/cmd/pbmigrate"
]
},
{
"name": "api", …
```
> chore: add JetBrains Fleet to gitignore

- CHANGELOG.md
SSIA
Congratulations to the release all! Great work.
```
lzap@mone provisioning-backend % g push upstream --tags --no-verify 
Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
To https://github.com/RHEnVision/provisioning-backend
* [new tag]         0.10.0 -> 0.10.0
```
> chore: version 0.10.0 and changelog

- .gitignore
- docs/dev-environment.md
> chore: add direnv.net to gitignore

- internal/config/config.go
> fix(config): correct Unleash URL prefix

- api/openapi.gen.json
- api/openapi.gen.yaml
- internal/dao/dao_interfaces.go
- internal/dao/pgx/reservation_pgx.go
- internal/dao/stubs/reservation_dao.go
- internal/dao/tests/reservation_test.go
- internal/payloads/reservation_payload.go
- internal/services/aws_reservation_service.go
- internal/services/reservations_service.go
- scripts/rest_examples/http-client.env.json
- scripts/rest_examples/reservation-get-1.http
SSIA
Fixes: https://issues.redhat.com/browse/HMSPROV-254
> feat: reservation detail returns instance ids

- internal/payloads/error_payload.go
We see an error in stage, this should show the root cause.
> fix: print full errors in logs

- internal/dao/stubs/model_factories.go
- internal/dao/stubs/reservation_dao.go
- internal/payloads/error_payload.go
- internal/services/reservations_service.go
- internal/services/reservations_service_test.go
Correctly render generic reservation on generic reservation endpoint.
Fixes HMSPROV-349
> fix(reservation): generic reservation by id

- cmd/pbstatuser/main.go
- deploy/clowdapp.yaml
- internal/kafka/topics.go
This adds the internal topic for the check.
> feat: availability check kafka topic

- CHANGELOG.md
> chore: version 0.11.0

- build/RedHat.dockerfile
- build/Upstream.dockerfile
- deploy/clowdapp.yaml
- mk/compile.mk
This adds the new statuser binary pod. I am getting everything ready to begin communicating messages.
> feat: statuser clowder deployment

- deploy/clowdapp.yaml
SSIA
At least until M0 is done.
> feat: increase default logging level to debug

- internal/kafka/kafka.go
Still hunting a misconfiguration in Clowder, this should confirm our topic is good.
> fix: log topic alongside trace send message

- internal/background/availability_queue_test.go
I don't see this on my laptop, but Go scheduler can decide not to run the enqueue goroutine which puts the message into the buffer, therefore the test sometimes fail on CI.
I do not want to create some complex synchronization test-only variables in order to wait until data goes through the channel, therefore I am using the `Sched()` function to allow for context switch and that itself should already help a lot.
But in case it would not, a small delay of 20 milliseconds should definitely do the work. Unless there is a bug in the code which I don't see.
> fix: intermittent failures on CI for ASM queue test

- internal/payloads/null_convert.go
- internal/payloads/reservation_payload.go
- internal/services/aws_reservation_service.go
https://issues.redhat.com/browse/HMSPROV-373
> fix: payload name not nullable

- CHANGELOG.md
- scripts/changelog.py
SSIA
Fixed a typo in the script.
> chore: version 0.12.0

- cmd/pbstatuser/main.go
- internal/background/availability_queue_test.go
- internal/ctxval/context_values.go
- internal/kafka/avail_status_msg.go
- internal/kafka/kafka.go
- internal/kafka/message.go
- internal/kafka/source_result.go
- internal/kafka/topics.go
- internal/services/availability_status_service.go
- scripts/kafka.start.sh
This draft PR is meant to align the usage of channels and go routines. 
It is missing:
- testing
> feat(HMSPROV-345): Add source check availability per each provider

- internal/payloads/error_payload.go
This should change the Version to BuildCommit
> fix(HMSPROV-368): change version to BuildCommit

- internal/config/helpers.go
- internal/kafka/kafka.go
- internal/kafka/source_result.go
- internal/kafka/topics.go
> fix: Use correct topic for sources availability check

- docs/dev-environment.md
> docs: kafka and worker info

- cmd/pbstatuser/main.go
- internal/metrics/metrics.go
Depends on https://github.com/RHEnVision/provisioning-backend/pull/349
> feat(HMSPROV-177): Add availability check request duration metric

- internal/config/config.go
- internal/config/validation.go
My last patch introduced a problem in config validation. Hopefully this fixes it and finally enables CW on stage.
> fix(HMSPROV-407): fix cw config validation

- internal/jobs/ensure_pubkey_on_aws_job.go
- internal/jobs/launch_instance_aws.go
- internal/jobs/launch_instance_gcp.go
SSIA, we had both in Kibana now it is just one field.
> chore: use reservation_id instead reservation

- internal/dao/tests/pubkey_resource_test.go
- internal/db/migrations/013_pubkey_resource_index.sql
Pubkey resource unique index was not changed after addition of source and region.
Refs HMSPROV-415
> fix: unique index on pubkey_resource

- cmd/pbstatuser/main.go
- internal/kafka/kafka.go
While the last patch fixed the kafka reader problem, I noticed that if the goroutine finishes execution for whatever reason, the app stays active. This patch fixes that, adds some extra logging and exits the application gracefully, so k8s can restart the container and notify us about it.
On top of that, I noticed some noisy debug messages, the patch removes those. I still want to keep debug mode on for some time, but the amount of these polling messages is flooding our logs.
> fix(HMSPROV-387): filter out noisy kafka logs

- deploy/dashboards/grafana-dashboard-provisioning.configmap.yaml
You can see the dashboard locally by importing it into Grafana. 
After this PR gets merged,  MR to app-stre needs to be pushed and merged to enable the dashboard deployment. 
_Reminder: It is the first version of the dashboard_
> feat(HMSPROV-428): Add provisioning dashboard

- internal/dao/pgx/service_pgx.go
- internal/migrations/code/update_fingerprints_test.go
> fix(HMSPROV-390): unscoped update pubkey fix

- pkg/worker/redis.go
When a fatal panic occurs (e.g. nil pointer dereference), the default behavior of the runtime is to exit immediately and terminate the program. This kills all other gorourines working on other jobs.
This patch changes the behavior, it is possible to setup the runtime in a way that all panics can be recovered and properly logged. Then the goroutine exists and other goroutines (jobs, pollers) can continue working on other jobs.
Example of such log during simulated nil pointer dereference:
```
2:43PM INF Dequeued job from Redis binary=pbworker hostname=mone.home.lan job_args={"AccountID":3,"Fail":false,"ReservationID":35} job_id=418e8a5a-2eca-4e17-b995-20d3b8c55a9a job_type=no_operation version=HEAD
2:43PM ERR Error during job handling: runtime error: invalid memory address or nil pointer …
```
> fix(HMSPROV-425): recover panics in workers

- cmd/pbstatuser/main.go
- internal/metrics/metrics.go
- internal/services/availability_status_service.go
TODO: after this pr is merged a change in the Grafana file needs to be done.
> feat(HMS-1122): Add total received availability check metric

- internal/clients/http/azure/create_vm.go
- internal/clients/interface.go
- internal/jobs/launch_instance_azure.go
- internal/services/azure_reservation_service.go
Split Resource group ensure into a job step.
Refs HMS-1165
This is a first split, I'll continue with this once we settle this is how we want to do it.
> refactor: Add step in Azure job

- internal/services/pubkey_service.go
We currently error out with "authentication for source not found" but there is nothing we can do when source is gone. Therefore we will just print warning in log instead and return 200.
https://issues.redhat.com/browse/HMS-1181
> fix(HMS-1181): ignore pubkey resource deletion without SA

- internal/clients/http/azure/create_vm.go
- internal/clients/interface.go
- internal/clients/stubs/azure_stub.go
- internal/clients/stubs/context_getters.go
- internal/clients/stubs/ec2_stub.go
- internal/clients/stubs/errors.go
- internal/clients/stubs/gcp_stub.go
- internal/clients/stubs/image_builder_stub.go
- internal/clients/stubs/sources_stub.go
- internal/jobs/launch_instance_aws_test.go
- internal/jobs/launch_instance_azure.go
- internal/jobs/launch_instance_azure_test.go
Add test for job deploying to Azure
Refs HMS-1058
> test: Add Azure task tests

- docs/configure-azure.md
- docs/lighthouse_template.json
Add docs on how to setup Azure account for testing the deployment.
Fixes HMS-1147
> docs: Document Azure setup

- deploy/testing.yaml
Updating stage testing marker(tekton only)
> ci: Change marker stage

- api/openapi.gen.json
- api/openapi.gen.yaml
- cmd/spec/path.yaml
Refs HMS-969
@adiabramovitch I guess we forgot this?
@akhil-jha do we want to cover this, or is this tiny enough?
> feat: add provider for Sources in OpenAPI spec

- deploy/clowdapp.yaml
SSIA
I am following our Floorist onboarding document, do not merge yet as we do not have the secret yet.
> fixes(HMSPROV-429): floorist exporter

- pkg/worker/redis.go
I noticed the read atomic overlook, a variable that must be threadsafe must be read and written via `atomic` function. This could possibly lead to stale value read.
Additionally, I noticed that the Redis client creates connection pool of CPUs * 10. We know for fact how big the pool should be - it needs to be numPollers + 1 + some room for statistics calls (usually just 1 but to give it some room 10 should be a good limit).
I renamed some variables to better reflect their purpose.
> fix(HMS-1242): atomically read statistics

- deploy/dashboards/grafana-dashboard-provisioning.configmap.yaml
Also added two panels to show the HTTP request latency and Source availability latency according to our SLOs
> fix(HMS-1259): Add adjustable datasource and SLOs panels

- cmd/typesctl/providers/ec2_types.go
- docs/preloading-cloud-data.md
This is a follow-up PR for https://github.com/RHEnVision/provisioning-backend/pull/433
It adds a documentation of the process, also added a missing newline from the std output.
> fix(HMS-951): region refresh docs

- api/openapi.gen.json
- api/openapi.gen.yaml
- cmd/spec/main.go
- cmd/spec/path.yaml
- internal/payloads/reservation_payload.go
Add OpenAPI endpoint for Azure reservation.
Fixes HMS-1182
> feat: Add Azure reservation to OpenAPI

- deploy/clowdapp.yaml
Set clowder to consume secrets for Azure client.
Fixes HMS-1374
> feat: consume Azure secret

- internal/metrics/metrics.go
> fix(HMS-879): missing metric registration

- internal/services/reservations_service.go
Implement Azure reservation details endpoint.
Fixes HMS-1393
> feat: Azure reservation details endpoint

- deploy/clowdapp.yaml
Trying annotation per pod. More info in the linked PR.
> chore: configure linter for 3-3-1 pod conf

- internal/clients/http/azure/create_vm.go
- internal/clients/interface.go
- internal/clients/stubs/azure_stub.go
- internal/jobs/launch_instance_azure.go
Enable support for poweroff flag.
Fixes HMS-1435
> feat: Azure support for cloud init

- deploy/clowdapp.yaml
SRE bot informs us about a check, we need to turn it off for statuser.
> chore: deployment is 3-3-1 replicas

- docs/adr/012-permissions-aws.md
> docs: Add Permissions Check ADR

- api/openapi.gen.json
- api/openapi.gen.yaml
- internal/clients/http/ec2/ec2_client.go
- internal/clients/http/ec2_errors.go
- internal/clients/http/sources/sources_client.go
- internal/clients/instance_description.go
- internal/clients/interface.go
- internal/clients/stubs/ec2_stub.go
- internal/dao/dao_interfaces.go
- internal/dao/pgx/reservation_pgx.go
- internal/dao/stubs/reservation_dao.go
- internal/jobs/launch_instance_aws.go
- internal/migrations/sql/019_add_detail_reservation_instances.sql
- internal/models/reservation_model.go
- internal/payloads/reservation_payload.go
- internal/services/aws_reservation_service.go
This adda fetching instance description to aws job, stores the instance's public ip and dns into reservation_instances table
I keep this PR as draft until UI is ready
> feat(HMS-761): add instance description to aws job

- internal/clients/http/ec2/ec2_client.go
- internal/clients/http/gcp/gcp_client.go
- internal/clients/instance_params.go
- internal/clients/interface.go
- internal/clients/stubs/ec2_stub.go
- internal/clients/stubs/gcp_stub.go
- internal/jobs/launch_instance_aws.go
- internal/jobs/launch_instance_gcp.go
Just an idea to simplify and have a cleaner interface
Would like to hear your opinion
Of course that this should be done for all providers and maybe for the responses as well.
> refactor: Create struct for InsertInstances request

- deploy/dashboards/grafana-dashboard-provisioning.configmap.yaml
- mk/dashboard.mk
- mk/z_common.mk
Forgot to call `make` this will not happen again since this PR is also adding a make check that will be executed by our CI.
> fix(HMS-1105): check for make dashboard target

- docs/adr/014-union-type-openapi.md
This is my proposal on how to solve union types in OpenAPI in a friendly manner for kin-openapi library we use.
> docs: union type openapi proposal

- docs/make.md
I don’t get why other PRs passed, I think the reason was that something passed tests before we implemented the CI check. This fixes it.
> chore: fix generated content

- docs/adr/013-add-provisioning-saga.md
Adding an ADR explaining the three option I have come up with regarding the Provisioning saga workflow
> docs: Add Provisioning saga workflow ADR

- api/openapi.gen.json
- api/openapi.gen.yaml
- internal/config/helpers.go
- internal/payloads/error_payload.go
I find sometimes difficult to find which Kibana should I start searching for. Error reports usually do not tell.
> feat: add environment to error message

- internal/services/azure_offering_template_service.go
Allow Azure to download the offering template.
Refs HMS-1148
> fix: Allow access from Azure portal

- internal/services/azure_offering_template_service.go
Add Allow header which seems to be the culprit for Azure.
> build: Add allow header on offering template

- internal/routes/all_routes.go
> fix: Allow OPTIONS method for Azure template

- internal/clients/http/azure/azure_client.go
- internal/clients/http/azure/azure_common.go
- internal/clients/http/azure/create_vm.go
- internal/clients/http/ec2/ec2_client.go
- internal/clients/http/gcp/gcp_client.go
- internal/clients/http/image_builder/image_client.go
- internal/clients/http/sources/sources_client.go
- internal/jobs/common.go
- internal/jobs/launch_instance_azure.go
- internal/telemetry/otel.go
Improving otel constants and adding more otel calls for sources and azure.
Also incorporated one small change from https://github.com/RHEnVision/provisioning-backend/pull/487 which I am going to close now.
> chore: more otel for some slow calls

- build/RedHat.dockerfile
Forgot to change this as well.
> build: use ubi9 runtime container

- .golangci.yml
- internal/clients/http/logging_doer.go
- internal/migrations/migrations.go
Upgrading Go version is hard. Next time I need to search for 1.19.
> build: update .golangci.yml

- mk/0_initial.mk
- mk/code.mk
- mk/compile.mk
> chore: improve make clean target

- deploy/clowdapp.yaml
> chore: introduce REST_ENDPOINTS_TRACE_DATA

- docs/configure-gcp.md
- internal/clients/http/gcp/gcp_client.go
- internal/dao/dao_interfaces.go
- internal/dao/pgx/reservation_pgx.go
- internal/dao/stubs/reservation_dao.go
- internal/payloads/reservation_payload.go
- internal/services/gcp_reservation_service.go
- internal/services/reservations_service.go
- scripts/rest_examples/reservation-get-1-gcp.http
This PR is Adding get GCP reservation by id as we have for Azure and for AWS.
> feat(HMS-1429): Add get gcp reservation by id 

- internal/clients/http/gcp/gcp_client.go
- internal/clients/instance_params.go
- internal/clients/interface.go
- internal/clients/stubs/gcp_stub.go
- internal/jobs/launch_instance_gcp.go
- internal/models/reservation_model.go
- internal/services/gcp_reservation_service.go
This PR partially depends on #468, in order to see that the instances description is available, still WIP. 
Wanted to hear your thoughts regarding the functions I have added to GCP's interface.   
It seems like there is only internal DNS available according to google docs, so currently I only added IPV4 info.
> feat(HMS-1773): Add IPv4 to GCP instance desc

- internal/clients/http/gcp/gcp_client.go
- internal/clients/interface.go
- internal/clients/stubs/gcp_stub.go
- internal/jobs/launch_instance_gcp.go
I got an error that a zone is required in the `GetInstanceRequest`, this PR fixes the issue.
> refactor: add zone info when listing instance desc

- deploy/clowdapp.yaml
For the superkey to work, we need superkey worker :)
> build: Add sources superkey as dependency

- docs/openapi.md
> fix(HMS-1616): cleanup reservation OpenAPI markdown

- api/openapi.gen.json
- api/openapi.gen.yaml
- cmd/spec/example_reservation.go
- cmd/spec/example_types.go
- cmd/spec/main.go
- cmd/spec/path.yaml
- internal/jobs/launch_instance_gcp.go
- internal/models/reservation_model.go
- internal/payloads/reservation_payload.go
- internal/services/gcp_reservation_service.go
- scripts/rest_examples/reservation-create-gcp.http
This PR depends on #468, and adds GCP to spec
> feat(HMS-1429): Add GCP to spec

- docs/configure-gcp.md
I'll keep that on draft until we get an ok from @akhil-jha
> refactor: Update permissions for provisioning role in GCP

- cmd/pbackend/api.go
- cmd/pbackend/statuser.go
- cmd/pbackend/worker.go
Just put all the code on the same level.
I tried to introduce a helper function but it did not work out, most of other initializations would not benefit from this. Introducing it just for these four lines is not necessary.
> feat(HMS-1550): improve initialization code for kafka

- internal/background/db_stats.go
- internal/background/queue_metrics.go
This slightly improves logging of the stats pod.
> fix(HMS-2002): cleanup stats logging

- internal/metrics/metrics.go
> fix(HMS-2002): database stats are in secs not ms

- docs/make.md
:wave: Noticed some changes to our Makefiles that were not documented.
> chore: Update Makefile doc

- deploy/cloudwash_job.yaml
Ref- https://issues.redhat.com/browse/HMS-1847
Utilize CloudWash and Tekton instance to regularly remove unused resources in our cloud accounts.
> chore(HMS-1847): A job for cloud resources cleanup

- internal/jobs/launch_instance_gcp.go
- internal/services/gcp_reservation_service.go
Adding fetching instances description step for GCP.
> feat(HMS-1955): Add fetch instances description step for GCP

- internal/clients/stubs/errors.go
- internal/clients/stubs/gcp_stub.go
- internal/dao/stubs/reservation_dao.go
- internal/jobs/launch_instance_azure_test.go
- internal/jobs/launch_instance_gcp_test.go
This PR  adds missing tests for GCP job: inserting instances and fetching instances description.
> refactor: Add GCP job test

- deploy/cloudwash_job.yaml
Ref- https://issues.redhat.com/browse/HMS-1847
> chore(HMS-1847): Update secretKeyRef name

- internal/config/config.go
Slightly improves errors, tho I am not sure if these structures are validated (required) or not in clowder.
> chore: better error when clowder is not present

- internal/kafka/kafka.go
It looks like some sources availability checks errors with 404 when we call sources. We are supposed to use the same identity which comes from sources and it looks we do.
However, in logging some org_id/account_numbers are not filled or do not match correctly. It looks like handling of identity is not correct and indeed the main consumer loop incorrectly overwrites the global context over and over again. This leads to random behavior when some messages using incorrect identities or logging incorrect data.
The proper way of dealing with contexts is to always create a copy of the global context, this ensures that only copies are passed into processing functions and they do not interfere with other goroutines.
> fix(HMS-2178): fix context handling in Kafka consumer

- deploy/clowdapp.yaml
> clowdapp: Fix typos

- .rhcicd/pr_check.sh
Same for frontend: https://github.com/RHEnVision/provisioning-frontend/pull/295
> ci: Update image UUIDs

- deploy/clowdapp.yaml
This prepares for our planned mainteinance this week.
> fix(HMS-2290): Make replicas configurable

- internal/clients/http/ec2/ec2_client.go
Otherwise it creates too many GlitchTip events:
https://glitchtip.devshift.net/insights/issues/958355?project=28
> chore: log EC2 client STS as warn

- CHANGELOG.md
Once we agree, we should first merge https://github.com/RHEnVision/changelog/pull/8
> docs: Makes scope links to Jira

- CHANGELOG.md
Regenerate changelog with links.
> docs: generate issue links

- api/openapi.gen.json
- api/openapi.gen.yaml
- cmd/spec/path.yaml
- internal/routes/all_routes.go
- internal/services/sources_service.go
SSIA
Can we do that now @ezr-ondrej ? All code gone from IB at this point?
> refactor: remove deprecated /account_identity

- deploy/clowdapp.yaml
This will allow us to understand possible issues with pending reservations. Hopefully all is resolved now, I still see 4 pending at the moment on stage so I would like to investigate.
> chore: add status and steps to floorist

- docs/adr/015-pagination.md
> docs(HMS-2316) Add pagination ADR

- deploy/cloudwash_job.yaml
> fix(HMS-1847): Cronjob template update

- internal/jobs/launch_instance_aws.go
A little bit more detailed logging. Public keys can be safely logged (private keys are not stored at all in our DB).
> chore: print pubkey on error

- deploy/clowdapp.yaml
> build(HMS-2743): Disable rbac caching temporarily

- deploy/clowdapp.yaml
Relates to https://github.com/RHEnVision/provisioning-backend/pull/699
> build(HMS-2743): Enable rbac caching

- api/openapi.gen.json
- api/openapi.gen.yaml
- cmd/spec/example_reservation.go
- internal/clients/http/azure/create_vms.go
- internal/jobs/launch_instance_azure.go
Fetch Azure private IP address as well as public one.
> feat(HMS-2439): Add private IP address in Azure details

- internal/background/db_stats.go
> chore: fix stats logging

- .rhcicd/pr_check.sh
Testing with different qe aws account
> ci: Update AWS account

- deploy/testing-integration.yaml
Adding _JAVA_OPTIONS for the selenium container.
**Checklist**
> ci: update testing-integration template parameters

- internal/clients/http/errors.go
- internal/clients/http/image_builder/image_client.go
- internal/clients/http/image_builder/image_client_test.go
- internal/clients/interface.go
- internal/clients/stubs/image_builder_stub.go
- internal/services/aws_reservation_service.go
- internal/services/azure_reservation_service.go
- internal/services/gcp_reservation_service.go
- scripts/rest_examples/reservation-create-aws-arm.http
This should enable arm64, it's not perfect for sure, but at least there's a test! :stuck_out_tongue: 
Refs HMS-1135
> feat: enable arm64 on AWS

- deploy/cloudwash_job.yaml
rebased @mayurilahane commit from #747 .
Meant to push to the pull ref on the remote but it created a branch, so I'm rolling with it.
> ci: Removing provider from env var

- config/api.env.example
- internal/config/config.go
- internal/db/connection.go
A small overlook, I decreased this value a bit few hours ago (from info to warning).
> chore: fix postgres logging

- internal/services/pubkey_service.go
This should fix the 500 status
> fix(HMS-2933): Fix validator DAO error

- internal/dao/stubs/pubkey_dao.go
- internal/services/pubkey_service_test.go
This is not perfect, because it duplicates the validation funcionality in the stub, so it still have untested paths (when we'd change validation in DAO, changed the DAO test, but forgotten to keep the stub validation up to date).
But IMO it's better then what we have no - no tests for validation on the handler level :)
> test: pubkey validation returns correct status

- internal/payloads/error_payload.go
- internal/services/aws_iam_service.go
- internal/services/sources_service_test.go
I will look into more NewClientErrors generated incorrectly
> fix(2933): Unify GetAuthentication handling

- internal/dao/dao_interfaces.go
> docs: fix StatDao documentation

- internal/ptr/any.go
> chore: document PtrOrEmpty

- deploy/cloudwash_job.yaml
parameterizing pod template to use Azure as well AWS for the cleanup.
> fix(HMS-1847):Aws_cloudwash_pipeline

- go.mod
- go.sum
- internal/config/ctx.go
- internal/config/flags.go
- internal/config/flags_listener.go
- internal/middleware/account.go
> chore: update unleash to v4

- internal/routes/all_routes.go
We have over 30k issues on stage, this is not a severe issue that is worth reporting.
> chore: lower severity on missing identity

- deploy/testing-integration.yaml
Name update from hms-integration to insights-experiences.
> ci(HMS-3962): Update Integration test image for IQE

- deploy/clowdapp.yaml
- renovate.json
Update deploy image to konflux image
> ci(KONFLUX-2339): Update cloud image to konflux

- mkdocs.yml
> Remove macros from techdocs plugins

- mkdocs.yml
> refactor: remove trailing space

- .tekton/provisioning-backend-pull-request.yaml
- .tekton/provisioning-backend-push.yaml
SSIA
Used https://github.com/simonbaird/konflux-pipeline-patcher/blob/main/specific-one-liners.md#sast-unicode-and-shell-check-tasks to generate this change for us.
> ci: add required SAST tasks to Konflux pipelines

- deploy/testing-integration.yaml
Testing enabling parallel execution for integration tests.
> test(RHINENG-14633): Parallel integration tests

- .tekton/provisioning-backend-pull-request.yaml
- .tekton/provisioning-backend-push.yaml
Update Konflux pipeline definitions
> ci: Konflux build pipeline service account migration
